refs$FrHa1994 <- bibentry(bibtype="Article",key="FrHa1994",
                             author=c(person(c("C"),"Friedrich"),person(c("W"),"Hagen")),
                             year=1994,title="Lipid contents of five species of notothenioid fish from high-Antarctic waters and ecological implications",
                             journal="Polar Biology",
                             volume=14,pages="359-369")

alleq_FrHa1994 <- function(id) {
    switch(id,
           ## Aethotaxis mitopteryx 234660, proper name is Aethotaxis mitopteryx mitopteryx
           "234661_LpDW~SL_FrHa1994"=list(taxon_name="Aethotaxis mitopteryx mitopteryx",
                                     taxon_aphia_id=234661,
                                     equation=function(...)tibble(allometric_value=43.3268+0.6676*...),
                                     inputs=tibble(property="standard length",units="cm",sample_minimum=20.0,sample_maximum=32.0),
                                     return_property="lipid content dry weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",9,
                                                         "R",0.687),
                                     notes="Digitized from Fig. 3A in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),
           "234661_LpDW~WW_FrHa1994"=list(taxon_name="Aethotaxis mitopteryx mitopteryx",
                                     taxon_aphia_id=234661,
                                     equation=function(...)tibble(allometric_value=53.9583+0.03499*...),
                                     inputs=tibble(property="wet weight",units="g",sample_minimum=105.0,sample_maximum=320.0),
                                     return_property="lipid content dry weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",9,
                                                         "R",0.696),
                                     notes="Digitized from Fig. 3B in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),
           ## Pleuragramma antarcticum 234721, proper name is Pleuragramma antarctica
           "712788_LpDW~SL_FrHa1994"=list(taxon_name="Pleuragramma antarctica",
                                     taxon_aphia_id=712788,
                                     equation=function(...)tibble(allometric_value=3.094+2.652*...),
                                     inputs=tibble(property="standard length",units="cm",sample_minimum=5.0,sample_maximum=19.0),
                                     return_property="lipid content dry weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",30,
                                                         "R",0.795),
                                     notes="Digitized from Fig. 3A in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),
           ## Trematomus lepidorhinus
           "234770_LpDW~SL_FrHa1994"=list(taxon_name="Trematomus lepidorhinus",
                                     taxon_aphia_id=234770,
                                     equation=function(...)tibble(allometric_value=1.392+1.122*...),
                                     inputs=tibble(property="standard length",units="cm",sample_minimum=10.5,sample_maximum=24.0),
                                     return_property="lipid content dry weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",39,
                                                         "R",0.553),
                                     notes="Digitized from Fig. 3A in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),

           stop("unrecognized equation ID: ",id))
}
