## otolith equations from Williams & McEldowney 1990
alleq_wm <- function(id) {
    switch(id,
           ## Bathylagus antarcticus
           "234631_SL~OL_WiMc1990"=list(taxon_name="Bathylagus antarcticus",
                                        taxon_aphia_id=234631,
                                        equation=function(...)tibble(allometric_value=56.16975*(...)-39.7831),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",17,
                                                            "R^2",0.875^2),
                                        reference=refs$WiMc1990),
           "234631_SL~OW_WiMc1990"=list(taxon_name="Bathylagus antarcticus",
                                        taxon_aphia_id=234631,
                                        equation=function(...)tibble(allometric_value=115.7744*(...)-47.0855),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",17,
                                                            "R^2",0.95^2),
                                        reference=refs$WiMc1990),
           "234631_mass~SL_WiMc1990"=list(taxon_name="Bathylagus antarcticus",
                                          taxon_aphia_id=234631,
                                          equation=function(...)tibble(allometric_value=(1.05e-06)*(...^3.446)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",196,
                                                              "R^2",0.993^2),
                                          reference=refs$WiMc1990),

           ## "Photichthys argenteus" valid name is Phosichthys argenteus
           ## Aphia ID 220007
           ## only raw data (N=4) given in WiMc1990

           ## Krefftichthys anderssoni
           "234641_SL~OL_WiMc1990"=list(taxon_name="Krefftichthys anderssoni",
                                        taxon_aphia_id=234641,
                                        equation=function(...)tibble(allometric_value=41.21040*(...)-13.8900),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",28,
                                                            "R^2",0.962^2),
                                        reference=refs$WiMc1990),
           "234641_SL~OW_WiMc1990"=list(taxon_name="Krefftichthys anderssoni",
                                        taxon_aphia_id=234641,
                                        equation=function(...)tibble(allometric_value=47.28366*(...)-9.10800),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",28,
                                                            "R^2",0.94^2),
                                        reference=refs$WiMc1990),
           "234641_mass~SL_WiMc1990"=list(taxon_name="Krefftichthys anderssoni",
                                          taxon_aphia_id=234641,
                                          equation=function(...)tibble(allometric_value=(3.220e-06)*(...^3.296)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",28,
                                                              "R^2",0.981^2),
                                          reference=refs$WiMc1990),

           ## Protomyctophum bolini
           "234714_SL~OL_WiMc1990"=list(taxon_name="Protomyctophum bolini",
                                        taxon_aphia_id=234714,
                                        equation=function(...)tibble(allometric_value=26.90736*...-5.68285),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",31,
                                                            "R^2",0.733^2),
                                        reference=refs$WiMc1990),
           "234714_SL~OW_WiMc1990"=list(taxon_name="Protomyctophum bolini",
                                        taxon_aphia_id=234714,
                                        equation=function(...)tibble(allometric_value=27.02152*...-6.38535),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",31,
                                                            "R^2",0.880^2),
                                        reference=refs$WiMc1990),
           "234714_mass~SL_WiMc1990"=list(taxon_name="Protomyctophum bolini",
                                          taxon_aphia_id=234714,
                                          equation=function(...)tibble(allometric_value=2.34e-05*(...^2.859)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",36,
                                                              "R^2",0.981^2),
                                          reference=refs$WiMc1990),

           ## Protomyctophum parallelum
           ## no equations, n=8 data only

           ## Electrona antarctica
           "217697_SL~OL_WiMc1990"=list(taxon_name="Electrona antarctica",
                                        taxon_aphia_id=217697,
                                        equation=function(...)tibble(allometric_value=42.69686*...+0.278033),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",86,
                                                            "R^2",0.984^2),
                                        reference=refs$WiMc1990),
           "217697_SL~OW_WiMc1990"=list(taxon_name="Electrona antarctica",
                                        taxon_aphia_id=217697,
                                        equation=function(...)tibble(allometric_value=33.30505*...+2.023806),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",85,
                                                            "R^2",0.988^2),
                                        reference=refs$WiMc1990),
           "217697_mass~SL_WiMc1990"=list(taxon_name="Electrona antarctica",
                                          taxon_aphia_id=217697,
                                          equation=function(...)tibble(allometric_value=9.53e-06*(...^3.080)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",227,
                                                              "R^2",0.988^2),
                                          reference=refs$WiMc1990),

           ## Electrona carlsbergi
           "234638_SL~OL_WiMc1990"=list(taxon_name="Electrona carlsbergi",
                                        taxon_aphia_id=234638,
                                        equation=function(...)tibble(allometric_value=24.25848*...-2.49594),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",20,
                                                            "R^2",0.960^2),
                                        reference=refs$WiMc1990),
           "234638_SL~OW_WiMc1990"=list(taxon_name="Electrona carlsbergi",
                                        taxon_aphia_id=234638,
                                        equation=function(...)tibble(allometric_value=23.38342*...-8.686356),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",20,
                                                            "R^2",0.917^2),
                                        reference=refs$WiMc1990),
           "234638_mass~SL_WiMc1990"=list(taxon_name="Electrona carlsbergi",
                                          taxon_aphia_id=234638,
                                          equation=function(...)tibble(allometric_value=5.314e-05*(...^2.737)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",20,
                                                              "R^2",0.970^2),
                                          reference=refs$WiMc1990),

           ## Electrona paucirastra
           ## 234779
           ## no equations, n=4 data

           ## Electrona subaspera
           "234791_SL~OL_WiMc1990"=list(taxon_name="Electrona subaspera",
                                        taxon_aphia_id=234791,
                                        equation=function(...)tibble(allometric_value=29.00713*...-9.04409),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",17,
                                                            "R^2",0.997^2),
                                        reference=refs$WiMc1990),
           "234791_SL~OW_WiMc1990"=list(taxon_name="Electrona subaspera",
                                        taxon_aphia_id=234791,
                                        equation=function(...)tibble(allometric_value=30.94086*...-8.10739),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",17,
                                                            "R^2",0.996^2),
                                        reference=refs$WiMc1990),
           "234791_mass~SL_WiMc1990"=list(taxon_name="Electrona subaspera",
                                          taxon_aphia_id=234791,
                                          equation=function(...)tibble(allometric_value=7.98e-06*(...^3.190)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",21,
                                                              "R^2",0.999^2),
                                          reference=refs$WiMc1990),

           ## Metelectrona ventralis
           ## no equations, n=7 data

           ## Gymnoscopelus braueri
           "234642_SL~OL_WiMc1990"=list(taxon_name="Gymnoscopelus braueri",
                                        taxon_aphia_id=234642,
                                        equation=function(...)tibble(allometric_value=43.34839*...-0.73401),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",41,
                                                            "R^2",0.904^2),
                                        reference=refs$WiMc1990),
           "234642_SL~OW_WiMc1990"=list(taxon_name="Gymnoscopelus braueri",
                                        taxon_aphia_id=234642,
                                        equation=function(...)tibble(allometric_value=50.27563*...-4.40964),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",41,
                                                            "R^2",0.943^2),
                                        reference=refs$WiMc1990),
           "234642_mass~SL_WiMc1990"=list(taxon_name="Gymnoscopelus braueri",
                                          taxon_aphia_id=234642,
                                          equation=function(...)tibble(allometric_value=5.639e-06*(...^3.102)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",41,
                                                              "R^2",0.986^2),
                                          reference=refs$WiMc1990),

           ## Gymnoscopelus bolini
           ## no equations, n=6 data

           ## Gymnoscopelus nicholsi
           "234821_SL~OL_WiMc1990"=list(taxon_name="Gymnoscopelus nicholsi",
                                        taxon_aphia_id=234821,
                                        equation=function(...)tibble(allometric_value=28.61827*...-20.7910),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",140,
                                                            "R^2",0.889^2),
                                        reference=refs$WiMc1990),
           "234821_SL~OW_WiMc1990"=list(taxon_name="Gymnoscopelus nicholsi",
                                        taxon_aphia_id=234821,
                                        equation=function(...)tibble(allometric_value=46.31267*...-17.2168),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",140,
                                                            "R^2",0.882^2),
                                        reference=refs$WiMc1990),
           "234821_mass~SL_WiMc1990"=list(taxon_name="Gymnoscopelus nicholsi",
                                          taxon_aphia_id=234821,
                                          equation=function(...)tibble(allometric_value=5.610e-06*(...^3.153)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",140,
                                                              "R^2",0.981^2),
                                          reference=refs$WiMc1990),

           ## Gymnoscopelus fraseri
           "234657_SL~OL_WiMc1990"=list(taxon_name="Gymnoscopelus fraseri",
                                        taxon_aphia_id=234657,
                                        equation=function(...)tibble(allometric_value=21.84513*...+1.731671),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",17,
                                                            "R^2",0.946^2),
                                        reference=refs$WiMc1990),
           "234657_SL~OW_WiMc1990"=list(taxon_name="Gymnoscopelus fraseri",
                                        taxon_aphia_id=234657,
                                        equation=function(...)tibble(allometric_value=29.47851*...+6.338667),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",17,
                                                            "R^2",0.892^2),
                                        reference=refs$WiMc1990),
           "234657_mass~SL_WiMc1990"=list(taxon_name="Gymnoscopelus fraseri",
                                          taxon_aphia_id=234657,
                                          equation=function(...)tibble(allometric_value=7.29e-06*(...^3.101)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",17,
                                                              "R^2",0.937^2),
                                          reference=refs$WiMc1990),

           ## Gymnoscopelus hintonoides
           ## no equations, n=6 data

           ## Gymnoscopelus microlampas
           ## no equations, n=1 data

           ## Gymnoscopelus piabilis
           ## no equations, n=2 data

           ## Lampanyctus australis
           ## no equations, n=1 data

           ## Diaphus hudsoni
           ## no equations, n=4 data

           ## Magnisudis prionosa
           ## no equations, n=0 data

           ## Notolepis coatsi
           ## no equations, n=2 data

           ## Benthalbella macropinna
           ## no equations, n=1

           ## Scopelarchoides kreefti
           ## no equations, n=1

           ## Muraenolepis marmoratus, valid name Muraenolepis marmorata
           "313346_SL~OL_WiMc1990"=list(taxon_name="Muraenolepis marmorata",
                                        taxon_aphia_id=313346,
                                        equation=function(...)tibble(allometric_value=45.75904*...+53.34070),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",28,
                                                            "R^2",0.563^2),
                                        reference=refs$WiMc1990),
           "313346_SL~OW_WiMc1990"=list(taxon_name="Muraenolepis marmorata",
                                        taxon_aphia_id=313346,
                                        equation=function(...)tibble(allometric_value=108.3560*...-68.3156),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",28,
                                                            "R^2",0.759^2),
                                        reference=refs$WiMc1990),
           "313346_mass~SL_WiMc1990"=list(taxon_name="Muraenolepis marmorata",
                                          taxon_aphia_id=313346,
                                          equation=function(...)tibble(allometric_value=9.065e-05*(...^2.589)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",28,
                                                              "R^2",0.950^2),
                                          reference=refs$WiMc1990),

           ## Macrourus holotrachys
           "234831_TL~OL_WiMc1990"=list(taxon_name="Macrourus holotrachys",
                                        taxon_aphia_id=234831,
                                        equation=function(...)tibble(allometric_value=40.23886*...-21.1335),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="total length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",15,
                                                            "R^2",0.951^2),
                                        reference=refs$WiMc1990),
           "234831_TL~OW_WiMc1990"=list(taxon_name="Macrourus holotrachys",
                                        taxon_aphia_id=234831,
                                        equation=function(...)tibble(allometric_value=105.0123*...-154.326),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="total length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",15,
                                                            "R^2",0.905^2),
                                        reference=refs$WiMc1990),
           "234831_mass~TL_WiMc1990"=list(taxon_name="Macrourus holotrachys",
                                          taxon_aphia_id=234831,
                                          equation=function(...)tibble(allometric_value=3.43e-07*(...^3.463)),
                                          inputs=tibble(property="total length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",14,
                                                              "R^2",0.995^2),
                                          reference=refs$WiMc1990),

           ## Zanclorhynchus spinifer
           "234683_SL~OL_WiMc1990"=list(taxon_name="Zanclorhynchus spinifer",
                                        taxon_aphia_id=234683,
                                        equation=function(...)tibble(allometric_value=4.088044*...+170.3344),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",65,
                                                            "R^2",0.101^2),
                                        reference=refs$WiMc1990),
           "234683_SL~OW_WiMc1990"=list(taxon_name="Zanclorhynchus spinifer",
                                        taxon_aphia_id=234683,
                                        equation=function(...)tibble(allometric_value=10.71815*...+163.0687),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",65,
                                                            "R^2",0.126^2),
                                        reference=refs$WiMc1990),
           "234683_mass~SL_WiMc1990"=list(taxon_name="Zanclorhynchus spinifer",
                                          taxon_aphia_id=234683,
                                          equation=function(...)tibble(allometric_value=1.63e-05*(...^3.047)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",152,
                                                              "R^2",0.993^2),
                                          reference=refs$WiMc1990),
           ## Dolloidraco longedorsali
           "234696_SL~OL_WiMc1990"=list(taxon_name="Dolloidraco longedorsali",
                                        taxon_aphia_id=234696,
                                        equation=function(...)tibble(allometric_value=10.28439*...+50.70341),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",33,
                                                            "R^2",0.674^2),
                                        reference=refs$WiMc1990),
           "234696_SL~OW_WiMc1990"=list(taxon_name="Dolloidraco longedorsali",
                                        taxon_aphia_id=234696,
                                        equation=function(...)tibble(allometric_value=14.15432*...+55.13149),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",33,
                                                            "R^2",0.571^2),
                                        reference=refs$WiMc1990),
           "234696_mass~SL_WiMc1990"=list(taxon_name="Dolloidraco longedorsali",
                                          taxon_aphia_id=234696,
                                          equation=function(...)tibble(allometric_value=3.86e-05*(...^2.84)),
                                          inputs=tibble(property="standard length",units="mm"),
                                          return_property="mass",
                                          return_units="g",
                                          reliability=tribble(~type,~value,
                                                              "N",47,
                                                              "R^2",0.914^2),
                                          reference=refs$WiMc1990),

           ## Histiodraco velifer, Pogonophryne barsukovi, Pogonophryne permitini
           ## no equations

           ## Pogonophryne phyllopogon, valid name is Pogonophryne scotti
           "234837_SL~OL_WiMc1990"=list(taxon_name="Pogonophryne scotti",
                                        taxon_aphia_id=234837,
                                          equation=function(...)tibble(allometric_value=30.64437*...+42.28450),
                                          inputs=tibble(property="otolith length",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",16,
                                                              "R^2",0.550^2),
                                          reference=refs$WiMc1990),
           "234837_SL~OW_WiMc1990"=list(taxon_name="Pogonophryne scotti",
                                        taxon_aphia_id=234837,
                                          equation=function(...)tibble(allometric_value=39.05815*...+47.90287),
                                          inputs=tibble(property="otolith width",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",16,
                                                              "R^2",0.537^2),
                                          reference=refs$WiMc1990),
           "234837_mass~SL_WiMc1990"=list(taxon_name="Pogonophryne scotti",
                                          taxon_aphia_id=234837,
                                            equation=function(...)tibble(allometric_value=4.78e-06*(...^3.343)),
                                            inputs=tibble(property="standard length",units="mm"),
                                            return_property="mass",
                                            return_units="g",
                                            reliability=tribble(~type,~value,
                                                                "N",18,
                                                                "R^2",0.986^2),
                                            reference=refs$WiMc1990),

           ## Pogonophryne ventrimaculata, Harpagifer georgianus georgianus, Aethotaxis mitopteryx
           ## no equations

           ## Dissostichus eleginoides
           "234700_SL~OL_WiMc1990"=list(taxon_name="Dissostichus eleginoides",
                                        taxon_aphia_id=234700,
                                          equation=function(...)tibble(allometric_value=73.86329*...-191.414),
                                          inputs=tibble(property="otolith length",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",160,
                                                              "R^2",0.916^2),
                                          reference=refs$WiMc1990),
           "234700_SL~OW_WiMc1990"=list(taxon_name="Dissostichus eleginoides",
                                        taxon_aphia_id=234700,
                                          equation=function(...)tibble(allometric_value=141.9414*...-264.490),
                                          inputs=tibble(property="otolith width",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",160,
                                                              "R^2",0.922^2),
                                          reference=refs$WiMc1990),
           "234700_mass~SL_WiMc1990"=list(taxon_name="Dissostichus eleginoides",
                                          taxon_aphia_id=234700,
                                            equation=function(...)tibble(allometric_value=4.59e-06*(...^3.187)),
                                            inputs=tibble(property="standard length",units="mm"),
                                            return_property="mass",
                                            return_units="g",
                                            reliability=tribble(~type,~value,
                                                                "N",159,
                                                                "R^2",0.985^2),
                                            reference=refs$WiMc1990),

           ## Dissostichus mawsoni
           "234836_SL~OL_WiMc1990"=list(taxon_name="Dissostichus mawsoni",
                                        taxon_aphia_id=234836,
                                          equation=function(...)tibble(allometric_value=90.83046*...-94.9810),
                                          inputs=tibble(property="otolith length",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",64,
                                                              "R^2",0.904^2),
                                          reference=refs$WiMc1990),
           "234836_SL~OW_WiMc1990"=list(taxon_name="Dissostichus mawsoni",
                                        taxon_aphia_id=234836,
                                          equation=function(...)tibble(allometric_value=97.36677*...-58.5629),
                                          inputs=tibble(property="otolith width",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",64,
                                                              "R^2",0.784^2),
                                          reference=refs$WiMc1990),
           "234836_mass~SL_WiMc1990"=list(taxon_name="Dissostichus mawsoni",
                                          taxon_aphia_id=234836,
                                            equation=function(...)tibble(allometric_value=2.17e-06*(...^3.317)),
                                            inputs=tibble(property="standard length",units="mm"),
                                            return_property="mass",
                                            return_units="g",
                                            reliability=tribble(~type,~value,
                                                                "N",72,
                                                                "R^2",0.994^2),
                                            reference=refs$WiMc1990),

           ## Notothenia coriiceps
           "234679_SL~OL_WiMc1990"=list(taxon_name="Notothenia coriiceps",
                                        taxon_aphia_id=234679,
                                          equation=function(...)tibble(allometric_value=86.59886*...-27.91347),
                                          inputs=tibble(property="otolith length",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",13,
                                                              "R^2",0.935^2),
                                          reference=refs$WiMc1990),
           "234679_SL~OW_WiMc1990"=list(taxon_name="Notothenia coriiceps",
                                        taxon_aphia_id=234679,
                                          equation=function(...)tibble(allometric_value=105.9125*...+110.2998),
                                          inputs=tibble(property="otolith width",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",13,
                                                              "R^2",0.700^2),
                                          reference=refs$WiMc1990),
           "234679_mass~SL_WiMc1990"=list(taxon_name="Notothenia coriiceps",
                                          taxon_aphia_id=234679,
                                            equation=function(...)tibble(allometric_value=2.78e-05*(...^2.943)),
                                            inputs=tibble(property="standard length",units="mm"),
                                            return_property="mass",
                                            return_units="g",
                                            reliability=tribble(~type,~value,
                                                                "N",20,
                                                                "R^2",0.988^2),
                                            reference=refs$WiMc1990),

           ## Notothenia neglecta
           "234740_SL~OL_WiMc1990"=list(taxon_name="Notothenia neglecta",
                                        taxon_aphia_id=234740,
                                          equation=function(...)tibble(allometric_value=71.41905*...+13.67271),
                                          inputs=tibble(property="otolith length",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",218,
                                                              "R^2",0.744^2),
                                          reference=refs$WiMc1990),
           "234740_SL~OW_WiMc1990"=list(taxon_name="Notothenia neglecta",
                                        taxon_aphia_id=234740,
                                          equation=function(...)tibble(allometric_value=112.1938*...+23.14088),
                                          inputs=tibble(property="otolith width",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",218,
                                                              "R^2",0.684^2),
                                          reference=refs$WiMc1990),
           "234740_mass~SL_WiMc1990"=list(taxon_name="Notothenia neglecta",
                                          taxon_aphia_id=234740,
                                            equation=function(...)tibble(allometric_value=5.71e-06*(...^3.259)),
                                            inputs=tibble(property="standard length",units="mm"),
                                            return_property="mass",
                                            return_units="g",
                                            reliability=tribble(~type,~value,
                                                                "N",264,
                                                                "R^2",0.974^2),
                                            reference=refs$WiMc1990),

           ## Notothenia rossii
           "234840_SL~OL_WiMc1990"=list(taxon_name="Notothenia rossii",
                                        taxon_aphia_id=234840,
                                          equation=function(...)tibble(allometric_value=82.58219*...+43.68991),
                                          inputs=tibble(property="otolith length",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",19,
                                                              "R^2",0.884^2),
                                          reference=refs$WiMc1990),
           "234840_SL~OW_WiMc1990"=list(taxon_name="Notothenia rossii",
                                        taxon_aphia_id=234840,
                                          equation=function(...)tibble(allometric_value=140.0371*...+50.05416),
                                          inputs=tibble(property="otolith width",units="mm"),
                                          return_property="standard length",
                                          return_units="mm",
                                          reliability=tribble(~type,~value,
                                                              "N",19,
                                                              "R^2",0.811^2),
                                          reference=refs$WiMc1990),
           "234840_mass~SL_WiMc1990"=list(taxon_name="Notothenia rossii",
                                          taxon_aphia_id=234840,
                                            equation=function(...)tibble(allometric_value=3.366e-06*(...^3.306)),
                                            inputs=tibble(property="standard length",units="mm"),
                                            return_property="mass",
                                            return_units="g",
                                            reliability=tribble(~type,~value,
                                                                "N",19,
                                                                "R^2",0.994^2),
                                            reference=refs$WiMc1990),












           ## Pleuragramma antarctica
           "712788_SL~OL_WiMc1990"=list(taxon_name="Pleuragramma antarctica",
                                        taxon_aphia_id=712788,
                                        equation=function(...)tibble(allometric_value=76.67621*(...)+0.1705014),
                                        inputs=tibble(property="otolith length",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",766,
                                                            "R^2",0.868^2),
                                        reference=refs$WiMc1990),
           "712788_SL~OW_WiMc1990"=list(taxon_name="Pleuragramma antarctica",
                                        taxon_aphia_id=712788,
                                        equation=function(...)tibble(allometric_value=69.21882*(...)+15.81990),
                                        inputs=tibble(property="otolith width",units="mm"),
                                        return_property="standard length",
                                        return_units="mm",
                                        reliability=tribble(~type,~value,
                                                            "N",759,
                                                            "R^2",0.906^2),
                                        reference=refs$WiMc1990),
           "712788_mass~SL_WiMc1990"=list(taxon_name="Pleuragramma antarctica",
                                        taxon_aphia_id=712788,
                                        equation=function(...)tibble(allometric_value=2.71e-06*(...^3.200)),
                                        inputs=tibble(property="standard length",units="mm"),
                                        return_property="mass",
                                        return_units="g",
                                        reliability=tribble(~type,~value,
                                                            "N",1297,
                                                            "R^2",0.992^2),
                                        reference=refs$WiMc1990),

           stop("unrecognized equation ID: ",id))
}
