refs$ArGo1991 <- bibentry(bibtype = "Article", key = "ArGo1991",
                          author = c(person(c("W", "E"), "Arntz"),
                                     person("M", "Gorny")),
                          year = 1991,
                          title = "Shrimp (Decapoda, Natantia) occurrence and distribution in the eastern Weddell Sea, Antarctica",
                          journal = "Polar Biology",
                          volume = 11, pages = "169-177", doi="10.1007/BF00240205")

refs$Rido1994 <- bibentry(bibtype = "Article", key = "Rido1994",
                          author = c(person("V", "Ridoux")),
                          year = 1994,
                          title = "The diets and dietary segregation of seabirds at the subantarctic Crozet Islands",
                          journal = "Marine Ornithology",
                          volume = 22, pages = "1-192")

refs$Kuun1999 <- bibentry(bibtype = "Article", key = "Kuun1999",
                          author = c(person("P", "Kuun"),
                                     person(c("E", "A"), "Pakhomov"),
                                     person(c("C", "D"), "McQuaid")),
                          year = 1990,
                          title = "Morphometric relationships of the caridean shrimp Nauticaris marionis Bate, 1888 at the Prince Edward Islands (Southern Ocean)",
                          journal = "Polar Biology",
                          volume = 22, pages = "216-218", doi="10.1007/s003000050413")

refs$TaLo2006 <- bibentry(bibtype = "Article", key = "TaLo2006",
                          author = c(person("F", "Tapella"),
                                     person(c("G", "A"), "Lovrich")),,
                          year = 2006,
                          title = "Morphological differences between 'subrugosa' and 'gregaria' morphs of adult Munida (Decapoda: Anomura: Galatheidae) from the Beagle Channel, southern South America",
                          journal = "Journal of the Marine Biological Association of the United Kingdom",
                          volume = 86, pages = "1149-1155")

alleq_crustaceans_other <- function(id) {
    switch(id,
           "369204_TL~CL_ArGo1991" = list(taxon_name = "Notocrangon antarcticus",
                                          taxon_aphia_id = 369204,
                                          equation = function(CL) tibble(allometric_value = 6.898 + 4.503*CL),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 8, sample_maximum = 27.1),
                                          return_property = "total length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 122,
                                                                "R^2", 0.98),
                                          reference=refs$ArGo1991),

           "369214_TL~CL_ArGo1991" = list(taxon_name = "Chorismus antarcticus",
                                          taxon_aphia_id = 369214,
                                          equation = function(CL) tibble(allometric_value = 8.436 + 4.739*CL),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 5, sample_maximum = 21.5),
                                          return_property = "total length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 120,
                                                                "R^2", 0.98),
                                          reference=refs$ArGo1991),

           "515320_WW~TL_Rido1994" = list(taxon_name = "Nauticaris marionis",
                                          taxon_aphia_id = 515320,
                                          equation = function(TL) tibble(allometric_value = 0.0053 * (TL^3.54)),
                                          inputs = tibble(property = "total length", units = "cm"),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 30,
                                                                "R", 0.98),
                                          reference=refs$Rido1994),


           "515320_WW~ED_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                          taxon_aphia_id = 515320,
                                          equation = function(ED) tibble(allometric_value = exp(3.2870*ED - 6.3465)),
                                          inputs = tibble(property = "eye diameter", units = "mm", sample_minimum = 0.82, sample_maximum = 2.18),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 457,
                                                                "R^2", 0.946),
                                          reference=refs$Kuun1999),

           "515320_DW~ED_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                          taxon_aphia_id = 515320,
                                          equation = function(ED) tibble(allometric_value = exp(3.5889*ED - 1.5512)),
                                          inputs = tibble(property = "eye diameter", units = "mm", sample_minimum = 0.90, sample_maximum = 1.90),
                                          return_property = "dry weight",
                                          return_units = "mg",
                                          reliability = tribble(~type, ~value,
                                                                "N", 212,
                                                                "R^2", 0.947),
                                          reference=refs$Kuun1999),

           "515320_AFDW~ED_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                            taxon_aphia_id = 515320,
                                            equation = function(ED) tibble(allometric_value = exp(3.5872*ED - 1.6819)),
                                            inputs = tibble(property = "eye diameter", units = "mm", sample_minimum = 0.90, sample_maximum = 1.90),
                                            return_property = "ash-free dry weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 211,
                                                                  "R^2", 0.953),
                                            reference=refs$Kuun1999),

           "515320_WW~CL_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                          taxon_aphia_id = 515320,
                                          equation = function(CL) tibble(allometric_value = exp(2.6520*log(CL) - 6.3154)),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 2.46, sample_maximum = 12.58),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 460,
                                                                "R^2", 0.970),
                                          reference=refs$Kuun1999),

           "515320_DW~CL_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                          taxon_aphia_id = 515320,
                                          equation = function(CL) tibble(allometric_value = exp(2.8471*log(CL) - 1.4548)),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 2.76, sample_maximum = 10.42),
                                          return_property = "dry weight",
                                          return_units = "mg",
                                          reliability = tribble(~type, ~value,
                                                                "N", 212,
                                                                "R^2", 0.963),
                                          reference=refs$Kuun1999),

           "515320_AFDW~CL_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                            taxon_aphia_id = 515320,
                                            equation = function(CL) tibble(allometric_value = exp(2.8188*log(CL) - 1.5459)),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 2.76, sample_maximum = 10.42),
                                            return_property = "ash-free dry weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 210,
                                                                  "R^2", 0.970),
                                            reference=refs$Kuun1999),

           "515320_WW~TL_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                          taxon_aphia_id = 515320,
                                          equation = function(TL) tibble(allometric_value = exp(3.3090*log(TL) - 12.2286)),
                                          inputs = tibble(property = "total length", units = "mm", sample_minimum = 21.1, sample_maximum = 48.1),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 188,
                                                                "R^2", 0.951),
                                          reference=refs$Kuun1999),

           "515320_CL~TL_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                          taxon_aphia_id = 515320,
                                          equation = function(TL) tibble(allometric_value = 0.2814*TL - 1.0512),
                                          inputs = tibble(property = "total length", units = "mm", sample_minimum = 21.1, sample_maximum = 48.1),
                                          return_property = "carapace length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 187,
                                                                "R^2", 0.959),
                                          reference=refs$Kuun1999),

           "515320_ED~CL_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                          taxon_aphia_id = 515320,
                                          equation = function(CL) tibble(allometric_value = exp(0.5830*log(CL) - 0.6881)),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 2.46, sample_maximum = 12.58),
                                          return_property = "eye diameter",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 455,
                                                                "R^2", 0.942),
                                          reference=refs$Kuun1999),

           "515320_DW~WW_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                          taxon_aphia_id = 515320,
                                          equation = function(WW) tibble(allometric_value = exp(1.0711*log(WW) + 5.3507)),
                                          inputs = tibble(property = "wet weight", units = "g", sample_minimum = 0.03, sample_maximum = 1.15),
                                          return_property = "dry weight",
                                          return_units = "mg",
                                          reliability = tribble(~type, ~value,
                                                                "N", 214,
                                                                "R^2", 0.981),
                                          reference=refs$Kuun1999),

           "515320_AFDW~WW_Kuun1999" = list(taxon_name = "Nauticaris marionis",
                                            taxon_aphia_id = 515320,
                                            equation = function(WW) tibble(allometric_value = exp(1.0666*log(WW) + 5.2078)),
                                            inputs = tibble(property = "wet weight", units = "g", sample_minimum = 0.03, sample_maximum = 1.15),
                                            return_property = "ash-free dry weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 213,
                                                                  "R^2", 0.983),
                                            reference=refs$Kuun1999),

           "392346M_WW~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                            taxon_aphia_id = 392346,
                                            equation = function(CL) tibble(allometric_value = exp(-3.242 + 3.053*log(CL))),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 15.4, sample_maximum = 28.1),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 24,
                                                                  "R^2", 0.99),
                                            notes = "Applies to male animals",
                                            reference=refs$TaLo2006),

           "392346F_WW~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                            taxon_aphia_id = 392346,
                                            equation = function(CL) tibble(allometric_value = exp(-2.903 + 2.800*log(CL))),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 16.2, sample_maximum = 26.5),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 23,
                                                                  "R^2", 0.99),
                                            notes = "Applies to female animals",
                                            reference=refs$TaLo2006),

           "392346_WW~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                          taxon_aphia_id = 392346,
                                          equation = function(CL) tibble(allometric_value = exp(-3.052 + 2.911*log(CL))),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 15.4, sample_maximum = 28.1),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 47,
                                                                "R^2", 0.99),
                                          notes = "Combined sample of 24 males and 23 females",
                                          reference=refs$TaLo2006),

           "392346M_DW~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                            taxon_aphia_id = 392346,
                                            equation = function(CL) tibble(allometric_value = exp(-3.638 + 2.958*log(CL))),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 15.4, sample_maximum = 28.1),
                                            return_property = "dry weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 24,
                                                                  "R^2", 0.96),
                                            notes = "Applies to male animals",
                                            reference=refs$TaLo2006),

           "392346F_DW~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                            taxon_aphia_id = 392346,
                                            equation = function(CL) tibble(allometric_value = exp(-3.128 + 2.566*log(CL))),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 16.2, sample_maximum = 26.5),
                                            return_property = "dry weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 23,
                                                                  "R^2", 0.93),
                                            notes = "Applies to female animals",
                                            reference=refs$TaLo2006),

           "392346_DW~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                          taxon_aphia_id = 392346,
                                          equation = function(CL) tibble(allometric_value = exp(-3.355 + 2.741*log(CL))),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 15.4, sample_maximum = 28.1),
                                          return_property = "dry weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 47,
                                                                "R^2", 0.97),
                                          notes = "Combined sample of 24 males and 23 females",
                                          reference=refs$TaLo2006),

           "392886M_WW~CL_TaLo2006" = list(taxon_name = "Munida subrugosa",
                                            taxon_aphia_id = 392886,
                                            equation = function(CL) tibble(allometric_value = exp(-3.335 + 3.150*log(CL))),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 13.3, sample_maximum = 28.0),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 32,
                                                                  "R^2", 0.99),
                                            notes = "Applies to male animals",
                                            reference=refs$TaLo2006),

           "392886F_WW~CL_TaLo2006" = list(taxon_name = "Munida subrugosa",
                                            taxon_aphia_id = 392886,
                                            equation = function(CL) tibble(allometric_value = exp(-3.034 + 2.914*log(CL))),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 14.4, sample_maximum = 24.1),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 30,
                                                                  "R^2", 0.98),
                                            notes = "Applies to female animals",
                                            reference=refs$TaLo2006),

           "392886M_DW~CL_TaLo2006" = list(taxon_name = "Munida subrugosa",
                                            taxon_aphia_id = 392886,
                                            equation = function(CL) tibble(allometric_value = exp(-4.181 + 3.397*log(CL))),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 13.3, sample_maximum = 28.0),
                                            return_property = "dry weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 32,
                                                                  "R^2", 0.99),
                                            notes = "Applies to male animals",
                                            reference=refs$TaLo2006),

           "392886F_DW~CL_TaLo2006" = list(taxon_name = "Munida subrugosa",
                                            taxon_aphia_id = 392886,
                                            equation = function(CL) tibble(allometric_value = exp(-3.552 + 2.894*log(CL))),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 14.4, sample_maximum = 24.1),
                                            return_property = "dry weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 30,
                                                                  "R^2", 0.95),
                                            notes = "Applies to female animals",
                                            reference=refs$TaLo2006),

           "392346_TL~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                          taxon_aphia_id = 392346,
                                          equation = function(CL) tibble(allometric_value = 0.719 + 1.229*CL),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 13.6, sample_maximum = 28.2),
                                          return_property = "total length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 55,
                                                                "R^2", 0.99),
                                          notes = "Combined sample of male and female animals",
                                          reference=refs$TaLo2006),

           "392346_ACW~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                           taxon_aphia_id = 392346,
                                           equation = function(CL) tibble(allometric_value = 1.366 + 0.556*CL),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 13.6, sample_maximum = 28.2),
                                           return_property = "anterior carapace width",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 55,
                                                                 "R^2", 0.98),
                                           notes = "Combined sample of male and female animals",
                                           reference=refs$TaLo2006),

           "392346_MCW~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                           taxon_aphia_id = 392346,
                                           equation = function(CL) tibble(allometric_value = -1.356 + 0.851*CL),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 13.6, sample_maximum = 28.2),
                                           return_property = "maximum carapace width",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 55,
                                                                 "R^2", 0.98),
                                           notes = "Combined sample of male and female animals",
                                           reference=refs$TaLo2006),

           "392346_RBW~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                           taxon_aphia_id = 392346,
                                           equation = function(CL) tibble(allometric_value = 0.545 + 0.143*CL),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 13.6, sample_maximum = 28.2),
                                           return_property = "rostrum basis width",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 55,
                                                                 "R^2", 0.87),
                                           notes = "Combined sample of male and female animals",
                                           reference=refs$TaLo2006),

           "392346_RL~CL_TaLo2006" = list(taxon_name = "Munida gregaria",
                                          taxon_aphia_id = 392346,
                                          equation = function(CL) tibble(allometric_value = 0.054 + 0.424*CL),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 13.6, sample_maximum = 28.2),
                                          return_property = "rostrum length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 55,
                                                                "R^2", 0.94),
                                          notes = "Combined sample of male and female animals",
                                          reference=refs$TaLo2006),

           "392886_TL~CL_TaLo2006" = list(taxon_name = "Munida subrugosa",
                                          taxon_aphia_id = 392886,
                                          equation = function(CL) tibble(allometric_value = 0.565 + 1.293*CL),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12.0, sample_maximum = 28.6),
                                          return_property = "total length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 57,
                                                                "R^2", 0.98),
                                          notes = "Combined sample of male and female animals",
                                          reference=refs$TaLo2006),

           "392886_ACW~CL_TaLo2006" = list(taxon_name = "Munida subrugosa",
                                           taxon_aphia_id = 392886,
                                           equation = function(CL) tibble(allometric_value = 0.825 + 0.572*CL),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12.0, sample_maximum = 28.6),
                                           return_property = "anterior carapace width",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 57,
                                                                 "R^2", 0.98),
                                           notes = "Combined sample of male and female animals",
                                           reference=refs$TaLo2006),

           "392886_MCW~CL_TaLo2006" = list(taxon_name = "Munida subrugosa",
                                           taxon_aphia_id = 392886,
                                           equation = function(CL) tibble(allometric_value = -1.033 + 0.860*CL),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12.0, sample_maximum = 28.6),
                                           return_property = "maximum carapace width",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 57,
                                                                 "R^2", 0.99),
                                           notes = "Combined sample of male and female animals",
                                           reference=refs$TaLo2006),

           "392886_RBW~CL_TaLo2006" = list(taxon_name = "Munida subrugosa",
                                           taxon_aphia_id = 392886,
                                           equation = function(CL) tibble(allometric_value = 0.239 + 0.130*CL),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12.0, sample_maximum = 28.6),
                                           return_property = "rostrum basis width",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 57,
                                                                 "R^2", 0.92),
                                           notes = "Combined sample of male and female animals",
                                           reference=refs$TaLo2006),

           "392886_RL~CL_TaLo2006" = list(taxon_name = "Munida subrugosa",
                                          taxon_aphia_id = 392886,
                                          equation = function(CL) tibble(allometric_value = 0.463 + 0.465*CL),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12.0, sample_maximum = 28.6),
                                          return_property = "rostrum length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 57,
                                                                "R^2", 0.89),
                                          notes = "Combined sample of male and female animals",
                                          reference=refs$TaLo2006),

           "173742_WW~TL_Rido1994" = list(taxon_name = "Lepas australis",
                                          taxon_aphia_id = 173742,
                                          equation = function(TL) tibble(allometric_value = 0.11 * (TL^3)),
                                          inputs = tibble(property = "total length", units = "cm"),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 11),
                                          notes = "Accepted name is Lepas (Anatifa) australis aphia_id 733349",
                                          reference=refs$Rido1994),

           "220837_WW~TL_Rido1994" = list(taxon_name = "Rhincalanus gigas",
                                          taxon_aphia_id = 220837,
                                          equation = function(TL) tibble(allometric_value = 0.018 * (TL^3)),
                                          inputs = tibble(property = "total length", units = "cm"),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 20),
                                          reference=refs$Rido1994),

           "237480_WW~TL_Rido1994" = list(taxon_name = "Gondogeneia spinicoxa",
                                          taxon_aphia_id = 237480,
                                          equation = function(TL) tibble(allometric_value = 0.02 * (TL^3.01)),
                                          inputs = tibble(property = "total length", units = "cm"),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 8,
                                                                "R", 0.97),
                                          notes = "The name given in the original publication was Gondogeneiella spinicoxa",
                                          reference=refs$Rido1994),

           "102564_WW~TL_Rido1994" = list(taxon_name = "Eurythenes obesus",
                                          taxon_aphia_id = 102564,
                                          equation = function(TL) tibble(allometric_value = 0.03 * (TL^3)),
                                          inputs = tibble(property = "total length", units = "cm"),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 3),
                                          reference=refs$Rido1994),

           stop("unrecognized equation ID: ",id))
}
