refs$Vane2005 <- bibentry(bibtype="Article",key="Vane2005",
                          author=c(person(c("F","A"),"Vanella"),person("J","Calvo"),person(c("E","R"),"Morriconi"),person(c("D","R"),"Aureliano")),
                          year=2005,title="Somatic energy content and histological analysis of the gonads in Antarctic fish from the Scotia Arc",
                          journal="Scientia Marina",
                          volume=69,pages="S2 305-316",doi="10.3989/scimar.2005.69s2305")

alleq_Vane2005 <- function(id) {
    switch(id,
           ## Chaenocephalus aceratus 78 0.0010·LT  3.44 0.96 8 0.0043·TL 3.53 0.99 78.8 1944 5.38 (0.45)
           "234725_WW~TL_Vane2005"=list(taxon_name="Chaenocephalus aceratus",
                                        taxon_aphia_id=234725,
                                        equation=function(...)tibble(allometric_value=0.0010*(...^3.44)),
                                        inputs=tibble(property="total length",units="cm"),
                                        return_property="wet weight",
                                        return_units="g",
                                        reliability=tribble(~type,~value,
                                                            "N",78,
                                                            "R^2",0.96),
                                        reference=refs$Vane2005),
           "234725_TEC~TL_Vane2005"=list(taxon_name="Chaenocephalus aceratus",
                                         taxon_aphia_id=234725,
                                         equation=function(...)tibble(allometric_value=0.0043*(...^3.53)),
                                         inputs=tibble(property="total length",units="cm"),
                                         return_property="total energy content",
                                         return_units="kJ",
                                         reliability=tribble(~type,~value,
                                                             "N",8,
                                                             "R^2",0.99),
                                         reference=refs$Vane2005),
           ## Champsocephalus gunnari 234797 76 0.0005·LT  3.76 0.95 5 0.4933·TL 2.28 0.47 76.8 2217 5.21 (0.50)
           "234797_WW~TL_Vane2005"=list(taxon_name="Champsocephalus gunnari",
                                        taxon_aphia_id=234797,
                                        equation=function(...)tibble(allometric_value=0.0005*(...^3.76)),
                                        inputs=tibble(property="total length",units="cm"),
                                        return_property="wet weight",
                                        return_units="g",
                                        reliability=tribble(~type,~value,
                                                            "N",76,
                                                            "R^2",0.95),
                                        reference=refs$Vane2005),
           "234797_TEC~TL_Vane2005"=list(taxon_name="Champsocephalus gunnari",
                                         taxon_aphia_id=234797,
                                         equation=function(...)tibble(allometric_value=0.4933*(...^2.28)),
                                         inputs=tibble(property="total length",units="cm"),
                                         return_property="total energy content",
                                         return_units="kJ",
                                         reliability=tribble(~type,~value,
                                                             "N",5,
                                                             "R^2",0.47),
                                         reference=refs$Vane2005),

           ## Pseudochaenichthys georgianus 234667 49 0.0008·LT  3.64 0.97 11 0.0003·TL 4.29 0.89 80.0 2238 4.55 (0.41)
           "234667_WW~TL_Vane2005"=list(taxon_name="Pseudochaenichthys georgianus",
                                        taxon_aphia_id=234667,
                                        equation=function(...)tibble(allometric_value=0.0008*(...^3.64)),
                                        inputs=tibble(property="total length",units="cm"),
                                        return_property="wet weight",
                                        return_units="g",
                                        reliability=tribble(~type,~value,
                                                            "N",49,
                                                            "R^2",0.97),
                                        reference=refs$Vane2005),
           "234667_TEC~TL_Vane2005"=list(taxon_name="Pseudochaenichthys georgianus",
                                         taxon_aphia_id=234667,
                                         equation=function(...)tibble(allometric_value=0.0003*(...^4.29)),
                                         inputs=tibble(property="total length",units="cm"),
                                         return_property="total energy content",
                                         return_units="kJ",
                                         reliability=tribble(~type,~value,
                                                             "N",11,
                                                             "R^2",0.89),
                                         reference=refs$Vane2005),

           ## Chionodraco rastrospinosus 234678 13 0.0040·LT  3.63 0.97 10 0.0040·TL  3.63 0.93 78.8 2615 4.99 (0.24)
           "234678_WW~TL_Vane2005"=list(taxon_name="Chionodraco rastrospinosus",
                                        taxon_aphia_id=234678,
                                        equation=function(...)tibble(allometric_value=0.0040*(...^3.63)),
                                        inputs=tibble(property="total length",units="cm"),
                                        return_property="wet weight",
                                        return_units="g",
                                        reliability=tribble(~type,~value,
                                                            "N",13,
                                                            "R^2",0.97),
                                        reference=refs$Vane2005),
           "234678_TEC~TL_Vane2005"=list(taxon_name="Chionodraco rastrospinosus",
                                         taxon_aphia_id=234678,
                                         equation=function(...)tibble(allometric_value=0.0040*(...^3.63)),
                                         inputs=tibble(property="total length",units="cm"),
                                         return_property="total energy content",
                                         return_units="kJ",
                                         reliability=tribble(~type,~value,
                                                             "N",10,
                                                             "R^2",0.93),
                                         reference=refs$Vane2005),

           ## Gobionotothen gibberifrons 234704 92 0.0015·LT  3.52 0.97 14 0.0028·TL  3.78 0.98 76.9 3183 4.89 (0.17)
           "234704_WW~TL_Vane2005"=list(taxon_name="Gobionotothen gibberifrons",
                                        taxon_aphia_id=234704,
                                        equation=function(...)tibble(allometric_value=0.0015*(...^3.52)),
                                        inputs=tibble(property="total length",units="cm"),
                                        return_property="wet weight",
                                        return_units="g",
                                        reliability=tribble(~type,~value,
                                                            "N",92,
                                                            "R^2",0.97),
                                        reference=refs$Vane2005),
           "234704_TEC~TL_Vane2005"=list(taxon_name="Gobionotothen gibberifrons",
                                         taxon_aphia_id=234704,
                                         equation=function(...)tibble(allometric_value=0.0028*(...^3.78)),
                                         inputs=tibble(property="total length",units="cm"),
                                         return_property="total energy content",
                                         return_units="kJ",
                                         reliability=tribble(~type,~value,
                                                             "N",14,
                                                             "R^2",0.98),
                                         reference=refs$Vane2005),

           ## Dissostichus eleginoides 234700 38 0.0249·LT  2.71 0.95 5 0.2216·TL  2.70 0.88 68.7 4689 7.80 (1.27)
           "234700_WW~TL_Vane2005"=list(taxon_name="Dissostichus eleginoides",
                                        taxon_aphia_id=234700,
                                        equation=function(...)tibble(allometric_value=0.0249*(...^2.71)),
                                        inputs=tibble(property="total length",units="cm"),
                                        return_property="wet weight",
                                        return_units="g",
                                        reliability=tribble(~type,~value,
                                                            "N",38,
                                                            "R^2",0.95),
                                        reference=refs$Vane2005),
           "234700_TEC~TL_Vane2005"=list(taxon_name="Dissostichus eleginoides",
                                         taxon_aphia_id=234700,
                                         equation=function(...)tibble(allometric_value=0.2216*(...^2.70)),
                                         inputs=tibble(property="total length",units="cm"),
                                         return_property="total energy content",
                                         return_units="kJ",
                                         reliability=tribble(~type,~value,
                                                             "N",5,
                                                             "R^2",0.88),
                                         reference=refs$Vane2005),

           ## Lepidonotothen kempi 313344 158 0.0042·LT  3.42 0.99 8 0.0279·TL  3.38 0.97 75.5 7253 5.40 (0.48)
           ## valid is Lepidonotothen squamifrons 234788
           "234788_WW~TL_Vane2005"=list(taxon_name="Lepidonotothen squamifrons",
                                        taxon_aphia_id=234788,
                                        equation=function(...)tibble(allometric_value=0.0042*(...^3.42)),
                                        inputs=tibble(property="total length",units="cm"),
                                        return_property="wet weight",
                                        return_units="g",
                                        reliability=tribble(~type,~value,
                                                            "N",158,
                                                            "R^2",0.99),
                                        reference=refs$Vane2005),
           "234788_TEC~TL_Vane2005"=list(taxon_name="Lepidonotothen squamifrons",
                                         taxon_aphia_id=234788,
                                         equation=function(...)tibble(allometric_value=0.0279*(...^3.38)),
                                         inputs=tibble(property="total length",units="cm"),
                                         return_property="total energy content",
                                         return_units="kJ",
                                         reliability=tribble(~type,~value,
                                                             "N",8,
                                                             "R^2",0.97),
                                         reference=refs$Vane2005),

           stop("unrecognized equation ID: ",id))
}
