refs$Goeb2007 <- bibentry(bibtype="Article",key="Goeb2007",
                             author=c(person(c("M","E"),"Goebel"),person(c("J","D"),"Lipsky"),person(c("C","S"),"Reiss"),person(c("V","J"),"Loeb")),
                             year=2007,
                             title="Using carapace measurements to determine the sex of Antarctic krill, Euphausia superba",
                             journal="Polar Biology",volume=30,pages="307-315",
                             doi="10.1007/s00300-006-0184-8")

refs$Morr1988 <- bibentry(bibtype="Article",key="Morr1988",
                             author=c(person(c("D","J"),"Morris"),person(c("J","L"),"Watkins"),person("C","Ricketts"),
                                      person("F","Buchholz"),person("J","Priddle")),
                             year=1988,
                             title="An assessmant of the merits of length and weight measurements of Antarctic krill Euphausia superba",
                             journal="British Antarctic Survey Bulletin",
                             volume=79,pages="27-50")

refs$Hewi2004 <- bibentry(bibtype="Article",key="Hewi2004",
                             author=c(person(c("R","P"),"Hewitt"),person("J","Watkins"),person("M","Naganobu"),
                                      person("V","Sushin"),person(c("A","S"),"Brierley"),person("D","Demer"),
                                      person("S","Kasatkina"),person("Y","Takao"),person("C","Goss"),
                                      person("A","Malyshko"),person("M","Brandon")),
                             year=2004,
                             title="Biomass of Antarctic krill in the Scotia Sea in January/February 2000 and its use in revising an estimate of precautionary yield",
                             journal="Deep Sea Research Part II: Topical Studies in Oceanography",
                             volume=51,pages="1215-1236",doi="10.1016/j.dsr2.2004.06.011")

refs$Mayz2003 <- bibentry(bibtype = "Article", key = "Mayz2003",
                          author = c(person("P", "Mayzaud"),
                                     person("M", "Boutoute"),
                                     person("F", "Alonzo")),
                          year = 2003,
                          title = "Lipid composition of the euphausiids Euphausia vallentini and Thysanoessa macrura during summer in the Southern Indian Ocean",
                          journal = "Antarctic Science",
                          volume = 15, pages = "463-475", doi = "10.1017/S0954102003001573")

##refs$Mayz1998 <- bibentry(bibtype = "Article", key = "Mayz1998",
##                          author = c(person("P", "Mayzaud"),
##                                     person("E", "Albessard"),
##                                     person("J", "Cuzin-Roudy")),
##                          year = 1998,
##                          title = "Changes in lipid composition of the Antarctic krill Euphausia superba  in the Indian sector of the Antarctic Ocean: influence of geographical location, sexual maturity stage and distribution among organs",
##                          journal = "Marine Ecology Progress Series",
##                          volume = 173, pages = "149-162", doi = "10.3354/meps173149")


##oldrefs$Goeb2007 <- "Goebel ME, Lipsky JD, Reiss CS, Loeb VJ (2007) Using carapace measurements to determine the sex of Antarctic krill, Euphausia superba. Polar Biology 30:307-315. doi:10.1007/s00300-006-0184-8"
##oldrefs$Morr1988 <- "Morris DJ, Watkins JL, Ricketts C, Buchholz F, Priddle J (1988) An assessmant of the merits of length and weight measurements of Antarctic krill Euphausia superba. British Antarctic Survey Bulletin 79:27-50"
##oldrefs$Hewi2004 <- "Hewitt RP, Watkins J, Naganobu M, Sushin V, Brierley AS, Demer D, Kasatkina S, Takao Y, Goss C, Malyshko A, Brandon M (2004) Biomass of Antarctic krill in the Scotia Sea in January/February 2000 and its use in revising an estimate of precautionary yield. Deep Sea Research Part II: Topical Studies in Oceanography 51:1215-1236. doi:10.1016/j.dsr2.2004.06.011"

alleq_krill <- function(id) {
    switch(id,
           "236217J_TL_Goeb2007"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(RCL)tibble(allometric_value=10.43+2.26*RCL),
                                     inputs=tibble(property="removed carapace length",units="mm",sample_minimum=9,sample_maximum=12),
                                     return_property="total length",
                                     return_units="mm",
                                     reliability=tribble(~type,~value,
                                                         "N",154,
                                                         "R^2",0.40),
                                     notes="Applies to juvenile animals",
                                     reference=refs$Goeb2007),
           "236217F_TL_Goeb2007"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(RCL)tibble(allometric_value=11.6+2.13*RCL),
                                     inputs=tibble(property="removed carapace length",units="mm",sample_minimum=9,sample_maximum=21),
                                     return_property="total length",
                                     return_units="mm",
                                     reliability=tribble(~type,~value,
                                                         "N",463,
                                                         "R^2",0.883),
                                     notes="Applies to adult female animals",
                                     reference=refs$Goeb2007),
           "236217M_TL_Goeb2007"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(RCL)tibble(allometric_value=0.62+3.13*RCL),
                                     inputs=tibble(property="removed carapace length",units="mm",sample_minimum=9,sample_maximum=18),
                                     return_property="total length",
                                     return_units="mm",
                                     reliability=tribble(~type,~value,
                                                         "N",514,
                                                         "R^2",0.777),
                                     notes="Applies to adult male animals",
                                     reference=refs$Goeb2007),

           "236217_WW_Morr1988"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(AT){ a <- 3.85; expon <- 3.20;
                                         out <- a*1e-06*(AT^expon)
                                         tibble(allometric_value=replace(out,AT<22 | AT>48,NA))},
                                     inputs=tibble(property="total length",units="mm",sample_minimum=22,sample_maximum=48),
                                     return_property="wet weight",
                                     return_units="g",
                                     reliability=tribble(~type,~value,
                                                         "N",4217),
                                     notes="Parameters from Morris et al. (1988) Table IV. Equation may not be valid outside of the range of data used to fit the equation; such values set to NA here",
                                     reference=refs$Morr1988),

           "236217_WW_Hewi2004"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(SL){ a <- 2.236; expon <- 3.314;
                                         out <- a*1e-06*(SL^expon)
                                         tibble(allometric_value=out)},
                                     inputs=tibble(property="standard length",units="mm"),
                                     return_property="wet weight",
                                     return_units="g",
                                     notes="Parameters from Hewitt et al. (2004) equ. 3",
                                     reference=refs$Hewi2004),

           ## Mayz2003
           ## Thysanoessa macrura  236219
           "236219A_WW~TL_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                                taxon_aphia_id = 236219,
                                                equation = function(TL) tibble(allometric_value = 10^(4.38 * log10(TL) - 3.64)),
                                                inputs = tibble(property = "total length", units = "mm"),
                                                return_property = "wet weight",
                                                return_units = "mg",
                                                reliability = tribble(~type, ~value,
                                                                      "N", 23,
                                                                      "R^2", 0.814),
                                                notes = "Applies to adult animals",
                                                reference = refs$Mayz2003),

           "236219J_WW~TL_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                                   taxon_aphia_id = 236219,
                                                   equation = function(TL) tibble(allometric_value = 10^(2.83 * log10(TL) - 1.72)),
                                                   inputs = tibble(property = "total length", units = "mm"),
                                                   return_property = "wet weight",
                                                   return_units = "mg",
                                                   reliability = tribble(~type, ~value,
                                                                         "N", 37,
                                                                         "R^2", 0.859),
                                                   notes = "Applies to juvenile animals",
                                                   reference = refs$Mayz2003),
           ## Euphausia vallentini  221054
           "221054M_WW~TL_Mayz2003" = list(taxon_name = "Euphausia vallentini",
                                           taxon_aphia_id = 221054,
                                           equation = function(TL) tibble(allometric_value = 10^(2.60 * log10(TL) - 1.53)),
                                           inputs = tibble(property = "total length", units = "mm"),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 57,
                                                                 "R^2", 0.804),
                                           notes = "Applies to male animals",
                                           reference = refs$Mayz2003),
           "221054F_WW~TL_Mayz2003" = list(taxon_name = "Euphausia vallentini",
                                           taxon_aphia_id = 221054,
                                           equation = function(TL) tibble(allometric_value = 10^(1.87 * log10(TL) - 0.52)),
                                           inputs = tibble(property = "total length", units = "mm"),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 71,
                                                                 "R^2", 0.575),
                                           notes = "Applies to female animals",
                                           reference = refs$Mayz2003),

           ## lipid weights to wet weights
           "221054_LpW~WW_Mayz2003" = list(taxon_name = "Euphausia vallentini",
                                           taxon_aphia_id = 221054,
                                           equation = function(WW) tibble(allometric_value = 10^(2.39 * log10(WW) - 5.01)),
                                           inputs = tibble(property = "wet weight", units = "mg"),
                                           return_property = "lipid weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 26,
                                                                 "R^2", 0.757),
                                           notes = "No difference between sexes observed, so equation was derived from data from males and females combined",
                                           reference = refs$Mayz2003),

           "236219F_LpW~WW_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(WW) tibble(allometric_value = 10^(2.86 * log10(WW) - 4.97)),
                                           inputs = tibble(property = "wet weight", units = "mg"),
                                           return_property = "lipid weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 17,
                                                                 "R^2", 0.792),
                                           notes = "Applies to female animals",
                                           reference = refs$Mayz2003),

           "236219M_LpW~WW_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                            taxon_aphia_id = 236219,
                                            equation = function(WW) tibble(allometric_value = 10^(1.53 * log10(WW) - 2.80)),
                                            inputs = tibble(property = "wet weight", units = "mg"),
                                            return_property = "lipid weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 6,
                                                                  "R^2", 0.835),
                                            notes = "Applies to male animals",
                                            reference = refs$Mayz2003),

           "236219J_LpW~WW_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                            taxon_aphia_id = 236219,
                                            equation = function(WW) tibble(allometric_value = 10^(1.04 * log10(WW) - 1.65)),
                                            inputs = tibble(property = "wet weight", units = "mg"),
                                            return_property = "lipid weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 37,
                                                                  "R^2", 0.300),
                                            notes = "Applies to juvenile animals",
                                            reference = refs$Mayz2003),


##           ## Mayzaud et al 1998
##           ## Euphausia superba 236217,
##           "236217_WW~TL_Mayz1998" = list(taxon_name="Euphausia superba",
##                                          taxon_aphia_id=236217,
##                                          equation = function(TL) tibble(allometric_value = 10^(-0.08 + 3.12 * log10(TL))),
##                                          inputs = tibble(property = "total length", units = "mm"),
##                                          return_property = "wet weight",
##                                          return_units = "mg",
##                                          reliability = tribble(~type, ~value,
##                                                                "N", 121,
##                                                                "R^2", 0.967),
##                                          notes = "Applies to males, females, and subadult animals",
##                                          reference = refs$Mayz1998),



           stop("unrecognized equation ID: ",id))
}
