refs$Goeb2007 <- "Goebel ME, Lipsky JD, Reiss CS, Loeb VJ (2007) Using carapace measurements to determine the sex of Antarctic krill, Euphausia superba. Polar Biology 30:307-315. doi:10.1007/s00300-006-0184-8"

alleq_Goeb2007 <- function(id) {
    switch(id,
           "236217J_TL_Goeb2007"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(RCL)tibble(allometric_value=10.43+2.26*RCL),
                                     inputs=tibble(property="removed carapace length",units="mm",sample_minimum=9,sample_maximum=12),
                                     return_property="total length",
                                     return_units="mm",
                                     reliability=tribble(~type,~value,
                                                         "N",154,
                                                         "R^2",0.40),
                                     notes="Applies to juvenile animals",
                                     reference=refs$Goeb2007),
           "236217F_TL_Goeb2007"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(RCL)tibble(allometric_value=11.6+2.13*RCL),
                                     inputs=tibble(property="removed carapace length",units="mm",sample_minimum=9,sample_maximum=21),
                                     return_property="total length",
                                     return_units="mm",
                                     reliability=tribble(~type,~value,
                                                         "N",463,
                                                         "R^2",0.883),
                                     notes="Applies to adult female animals",
                                     reference=refs$Goeb2007),
           "236217M_TL_Goeb2007"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(RCL)tibble(allometric_value=0.62+3.13*RCL),
                                     inputs=tibble(property="removed carapace length",units="mm",sample_minimum=9,sample_maximum=18),
                                     return_property="total length",
                                     return_units="mm",
                                     reliability=tribble(~type,~value,
                                                         "N",514,
                                                         "R^2",0.777),
                                     notes="Applies to adult male animals",
                                     reference=refs$Goeb2007),

           stop("unrecognized equation ID: ",id))
}
