refs$FrHa1994 <- bibentry(bibtype="Article",key="FrHa1994",
                             author=c(person(c("C"),"Friedrich"),person(c("W"),"Hagen")),
                             year=1994,title="Lipid contents of five species of notothenioid fish from high-Antarctic waters and ecological implications",
                             journal="Polar Biology",
                             volume=14,pages="359-369")

alleq_FrHa1994 <- function(id) {
    switch(id,
           ## Aethotaxis mitopteryx 234660, proper name is Aethotaxis mitopteryx mitopteryx
           "234661_LpDW~SL_FrHa1994"=list(taxon_name="Aethotaxis mitopteryx mitopteryx",
                                     taxon_aphia_id=234661,
                                     equation=function(...)tibble(allometric_value=43.3268+0.6676*...),
                                     inputs=tibble(property="standard length",units="cm",sample_minimum=20.0,sample_maximum=32.0),
                                     return_property="lipid content dry weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",9,
                                                         "R",0.687),
                                     notes="Digitized from Fig. 3A in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),
           "234661_LpDW~WW_FrHa1994"=list(taxon_name="Aethotaxis mitopteryx mitopteryx",
                                     taxon_aphia_id=234661,
                                     equation=function(...)tibble(allometric_value=53.9583+0.03499*...),
                                     inputs=tibble(property="wet weight",units="g",sample_minimum=105.0,sample_maximum=320.0),
                                     return_property="lipid content dry weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",9,
                                                         "R",0.696),
                                     notes="Digitized from Fig. 3B in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),
           "234661_WC~LpWW_FrHa1994"=list(taxon_name="Aethotaxis mitopteryx mitopteryx",
                                     taxon_aphia_id=234661,
                                     equation=function(...)tibble(allometric_value=56.861-2.143*...),
                                     inputs=tibble(property="lipid content wet weight",units="%",sample_minimum=20.0,sample_maximum=26.0),
                                     return_property="water content wet weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",9,
                                                         "R",0.938),
                                     notes="Digitized from Fig. 5 in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),

           ## Pleuragramma antarcticum 234721, proper name is Pleuragramma antarctica
           "712788_LpDW~SL_FrHa1994"=list(taxon_name="Pleuragramma antarctica",
                                     taxon_aphia_id=712788,
                                     equation=function(...)tibble(allometric_value=3.094+2.652*...),
                                     inputs=tibble(property="standard length",units="cm",sample_minimum=5.0,sample_maximum=19.0),
                                     return_property="lipid content dry weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",30,
                                                         "R",0.795),
                                     notes="Digitized from Fig. 3A in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),
           "712788_WC~LpWW_FrHa1994"=list(taxon_name="Pleuragramma antarctica",
                                     taxon_aphia_id=712788,
                                     equation=function(...)tibble(allometric_value=92.924-3.681*...),
                                     inputs=tibble(property="lipid content wet weight",units="%",sample_minimum=1.2,sample_maximum=15.8),
                                     return_property="water content wet weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",30,
                                                         "R",0.994),
                                     notes="Digitized from Fig. 5 in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),

           ## Trematomus lepidorhinus
           "234770_LpDW~SL_FrHa1994"=list(taxon_name="Trematomus lepidorhinus",
                                     taxon_aphia_id=234770,
                                     equation=function(...)tibble(allometric_value=1.392+1.122*...),
                                     inputs=tibble(property="standard length",units="cm",sample_minimum=10.5,sample_maximum=24.0),
                                     return_property="lipid content dry weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",39,
                                                         "R",0.553),
                                     notes="Digitized from Fig. 3A in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),
           "234770_WC~LpWW_FrHa1994"=list(taxon_name="Trematomus lepidorhinus",
                                     taxon_aphia_id=234770,
                                     equation=function(...)tibble(allometric_value=67.089-4.151*...),
                                     inputs=tibble(property="lipid content wet weight",units="%",sample_minimum=2.2,sample_maximum=13.2),
                                     return_property="water content wet weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",39,
                                                         "R",0.881),
                                     notes="Digitized from Fig. 5 in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),

           ## Bathydraco marri
           "234816_WC~LpWW_FrHa1994"=list(taxon_name="Bathydraco marri",
                                     taxon_aphia_id=234816,
                                     equation=function(...)tibble(allometric_value=58.476-2.949*...),
                                     inputs=tibble(property="lipid content wet weight",units="%",sample_minimum=0.7,sample_maximum=8.2),
                                     return_property="water content wet weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",16,
                                                         "R",0.982),
                                     notes="Digitized from Fig. 5 in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),

           ## Dolloidraco longedorsalis
           "234696_WC~LpWW_FrHa1994"=list(taxon_name="Dolloidraco longedorsalis",
                                     taxon_aphia_id=234696,
                                     equation=function(...)tibble(allometric_value=82.330-9.755*...),
                                     inputs=tibble(property="lipid content wet weight",units="%",sample_minimum=1.1,sample_maximum=4.0),
                                     return_property="water content wet weight",
                                     return_units="%",
                                     reliability=tribble(~type,~value,
                                                         "N",15,
                                                         "R",0.731),
                                     notes="Digitized from Fig. 5 in Friedrich & Hagen (1994)",
                                     reference=refs$FrHa1994),

           stop("unrecognized equation ID: ",id))
}
