refs$LaMe2000 <- bibentry(bibtype = "Article", key = "LaMe2000",
                          author = c(person(c("M"), "La Mesa"),
                                     person(c("M"), "Vacchi"),
                                     person("T", "Zunini Sertorio")),
                          year = 2000,
                          title = "Feeding plasticity of Trematomus newnesi (Pisces, Nototheniidae) in Terra Nova Bay, Ross Sea, in relation to environmental conditions",
                          journal = "Polar Biology",
                          volume = 23, pages = "38-45", doi="10.1007/s003000050006")

refs$LaMe2018 <- bibentry(bibtype = "Article", key = "LaMe2018",
                          author = c(person("M", "La Mesa"),
                                     person("F", "Donato"),
                                     person("E", "Riginella"),
                                     person("C", "Mazzoldi")),
                          year = 2018,
                          title = "Life history traits of a poorly known pelagic fish, Aethotaxis mitopteryx (Perciformes, Notothenioidei) from the Weddell Sea",
                          journal = "Polar Biology",
                          volume = 41, pages = "1777-1788", doi="10.1007/s00300-018-2318-1")

refs$Troc2020 <- bibentry(bibtype = "Article", key = "Troc2020",
                          author = c(person("Gonzalo Horacio", "Troccoli"),
                                     person("Eduardo", "Aguilar"),
                                     person("Patricia Alejandra", "Mart\uednez"),
                                     person("Mauro", "Belleggia")),
                          year = 2020,
                          title = "The diet of the Patagonian toothfish Dissostichus eleginoides, a deep-sea top predator of Southwest Atlantic Ocean",
                          journal = "Polar Biology",
                          volume = 43, pages = "1595-1604", doi="10.1007/s00300-020-02730-2")

refs$Llom2020 <- bibentry(bibtype = "Article", key = "Llom2020",
                          author = c(person("Facundo M", "Llompart"),
                                     person("Daniel A", "Fern\ue1ndez"),
                                     person("Daniel", "Aureliano"),
                                     person("Mario", "La Mesa")),
                          year = 2020,
                          title = "Life-history traits of the Magellan plunderfish Harpagifer bispinis (Forster, 1801) in the Beagle Channel (Tierra del Fuego, South America)",
                          journal = "Polar Biology",
                          volume = 43, pages = "1643-1654", doi="10.1007/s00300-020-02735-x")

refs$Pink2013 <- bibentry(bibtype = "Article", key = "Pink2013",
                          author = c(person("MH", "Pinkerton"),
                                     person("P", "McMillan"),
                                     person("J", "Forman"),
                                     person("P", "Marriot"),
                                     person("P", "Horn"),
                                     person("S", "Bury"),
                                     person("J", "Brown")),
                          year = 2013,
                          title = "Distribution, morphology and ecology of Macrourus whitsoni and M. caml (Gadiformes, Macrouridae) in the Ross Sea region",
                          journal = "CCAMLR Science",
                          ## url = "https://www.ccamlr.org/en/publications/science_journal/ccamlr-science-volume-20/37-61",
                          volume = 20, pages = "37-61", doi="10.1007/s00300-020-02735-x")


alleq_fish_other <- function(id) {
    switch(id,
           ## Trematomus newnesi 234628
           "234628_WW~TL_Dec_LaMe2000" = list(taxon_name = "Trematomus newnesi",
                                             taxon_aphia_id = 234628,
                                             equation = function(TL) tibble(allometric_value = 2.07e-03 * (TL ^ 2.01)),
                                             inputs = tibble(property = "total length", units = "mm"),
                                             return_property = "wet weight",
                                             return_units = "g",
                                             reliability = tribble(~type, ~value,
                                                                   "N", 43,
                                                                   "R^2", 0.74),
                                             notes="Calculated on specimens of both sexes, collected during December 1994",
                                             reference=refs$LaMe2000),

           "234628_WW~TL_Feb_LaMe2000" = list(taxon_name = "Trematomus newnesi",
                                             taxon_aphia_id = 234628,
                                             equation = function(TL) tibble(allometric_value = 2.41e-06 * (TL ^ 3.27)),
                                             inputs = tibble(property = "total length", units = "mm"),
                                             return_property = "wet weight",
                                             return_units = "g",
                                             reliability = tribble(~type, ~value,
                                                                   "N", 49,
                                                                   "R^2", 0.88),
                                             notes="Calculated on specimens of both sexes, collected during February 1998",
                                             reference=refs$LaMe2000),

           ## Aethotaxis mitopteryx, accepted name is Aethotaxis mitopteryx mitopteryx
           "234661F_WW~SL_LaMe2018" = list(taxon_name = "Aethotaxis mitopteryx mitopteryx",
                                          taxon_aphia_id = 234661,
                                          equation = function(SL) tibble(allometric_value = 0.0057 * (SL ^ 3.20)),
                                          inputs = tibble(property = "standard length", units = "cm", sample_minimum = 18, sample_maximum = 45),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 44),
                                          notes="Applies to female animals",
                                          reference=refs$LaMe2018),

           "234661M_WW~SL_LaMe2018" = list(taxon_name = "Aethotaxis mitopteryx mitopteryx",
                                           taxon_aphia_id = 234661,
                                           equation = function(SL) tibble(allometric_value = 0.0111 * (SL ^ 2.99)),
                                           inputs = tibble(property = "standard length", units = "cm", sample_minimum = 13, sample_maximum = 31),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 35),
                                           notes="Applies to male animals",
                                           reference=refs$LaMe2018),

           "234661_SL~OL_LaMe2018" = list(taxon_name = "Aethotaxis mitopteryx mitopteryx",
                                          taxon_aphia_id = 234661,
                                          equation = function(OL) tibble(allometric_value = -1.95 + 5.24 * OL),
                                          inputs = tibble(property = "otolith length", units = "mm", sample_minimum = 3.2, sample_maximum = 9.4),
                                          return_property = "standard length",
                                          return_units = "cm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 73,
                                                                "R^2", 0.91),
                                          notes="Derived from otoliths of animals of both sexes",
                                          reference=refs$LaMe2018),

           "234700_WW~TL_Troc2020" = list(taxon_name = "Dissostichus eleginoides",
                                          taxon_aphia_id = 234700,
                                          equation = function(TL) tibble(allometric_value = 6.92e-06 * (TL^3.08)),
                                          inputs = tibble(property = "total length", units = "cm", sample_minimum = 38, sample_maximum = 190),
                                          return_property = "wet weight", return_units = "kg",
                                          reliability = tribble(~type, ~value,
                                                                "N", 318,
                                                                "R^2", 0.98),
                                          reference = refs$Troc2020),

           "234626_WW~TL_Llom2020" = list(taxon_name = "Harpagifer bispinus",
                                          taxon_aphia_id = 234626,
                                          equation = function(TL) tibble(allometric_value = 0.0000237 * (TL^2.88)),
                                          inputs = tibble(property = "total length", units = "mm", sample_minimum = 38, sample_maximum = 80),
                                          return_property = "wet weight", return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 99+84),
                                          reference = refs$Llom2020),

           "234626_TL~age_Llom2020" = list(taxon_name = "Harpagifer bispinus",
                                           taxon_aphia_id = 234626,
                                           equation = function(t) sol_vonbert(t, Linf = 80.7, k = 0.25, t0 = -2.31, Linf_se = 0.82, k_se = 0.01, t0_se = 0),
                                           inputs = tibble(property = "age", units = "yr", sample_minimum = 0.5, sample_maximum = 7),
                                           return_property = "total length",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                   "N", 99+84),
                                           notes = "von Bertalanffy growth function for male and female animals combined",
                                           reference = refs$Llom2020),

           "712470F_WW~TL_Pink2013" = list(taxon_name = "Macrourus caml",
                                           taxon_aphia_id = 712470,
                                           equation = function(TL) tibble(allometric_value = 0.00216 * (TL ^ 3.234)),
                                           inputs = tibble(property = "total length", units = "cm", sample_minimum = 34.5, sample_maximum = 84),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 380),
                                           notes="Applies to female animals",
                                           reference=refs$Pink2013),

           "712470F_WW~PAL_Pink2013" = list(taxon_name = "Macrourus caml",
                                            taxon_aphia_id = 712470,
                                            equation = function(PAL) tibble(allometric_value = 0.076 * (PAL ^ 3.186)),
                                            inputs = tibble(property = "pre-anal length", units = "cm"),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 380),
                                            notes="Applies to female animals",
                                            reference=refs$Pink2013),

           "712470M_WW~TL_Pink2013" = list(taxon_name = "Macrourus caml",
                                           taxon_aphia_id = 712470,
                                           equation = function(TL) tibble(allometric_value = 0.00366 * (TL ^ 3.060)),
                                           inputs = tibble(property = "total length", units = "cm", sample_minimum = 34.5, sample_maximum = 74.5),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 252),
                                           notes="Applies to male animals",
                                           reference=refs$Pink2013),

           "712470M_WW~PAL_Pink2013" = list(taxon_name = "Macrourus caml",
                                            taxon_aphia_id = 712470,
                                            equation = function(PAL) tibble(allometric_value = 0.124 * (PAL ^ 3.016)),
                                            inputs = tibble(property = "pre-anal length", units = "cm"),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 252,
                                                                  "R^2", 0.87),
                                            notes="Applies to male animals",
                                            reference=refs$Pink2013),

           "234606_WW~TL_Pink2013" = list(taxon_name = "Macrourus whitsoni",
                                          taxon_aphia_id = 234606,
                                          equation = function(TL) tibble(allometric_value = 0.00366 * (TL ^ 3.060)),
                                          inputs = tibble(property = "total length", units = "cm", sample_minimum = 34.5, sample_maximum = 65.1),
                                          return_property = "wet weight",
                                          return_units = "g",
                                          reliability = tribble(~type, ~value,
                                                                "N", 226),
                                          notes="Combined sample of male and female animals",
                                          reference=refs$Pink2013),

           "234606_WW~PAL_Pink2013" = list(taxon_name = "Macrourus whitsoni",
                                           taxon_aphia_id = 234606,
                                           equation = function(PAL) tibble(allometric_value = 0.237 * (PAL ^ 2.722)),
                                           inputs = tibble(property = "pre-anal length", units = "cm"),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 226,
                                                                 "R^2", 0.87),
                                           notes="Combined sample of male and female animals",
                                           reference=refs$Pink2013),

           "234606_PAL~TL_Pink2013" = list(taxon_name = "Macrourus whitsoni",
                                           taxon_aphia_id = 234606,
                                           equation = function(TL) tibble(allometric_value = 0.14 + 0.344 * TL),
                                           inputs = tibble(property = "total length", units = "cm", sample_minimum = 34.5, sample_maximum = 65.1),
                                           return_property = "pre-anal length",
                                           return_units = "cm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 226),
                                           notes="Combined sample of male and female animals",
                                           reference=refs$Pink2013),

           "234606_TL~PAL_Pink2013" = list(taxon_name = "Macrourus whitsoni",
                                           taxon_aphia_id = 234606,
                                           equation = function(PAL) tibble(allometric_value = 4.38 + 2.65 * PAL),
                                           inputs = tibble(property = "pre-anal length", units = "cm"),
                                           return_property = "total length",
                                           return_units = "cm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 226),
                                           notes="Combined sample of male and female animals",
                                           reference=refs$Pink2013),

           "712470F_PAL~TL_Pink2013" = list(taxon_name = "Macrourus caml",
                                            taxon_aphia_id = 712470,
                                            equation = function(TL) tibble(allometric_value = 0.14 + 0.344 * TL),
                                            inputs = tibble(property = "total length", units = "cm", sample_minimum = 34.5, sample_maximum = 84),
                                            return_property = "pre-anal length",
                                            return_units = "cm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 380),
                                            notes="Applies to female animals",
                                            reference=refs$Pink2013),

           "712470F_TL~PAL_Pink2013" = list(taxon_name = "Macrourus caml",
                                            taxon_aphia_id = 712470,
                                            equation = function(PAL) tibble(allometric_value = 4.38 + 2.65 * PAL),
                                            inputs = tibble(property = "pre-anal length", units = "cm"),
                                            return_property = "total length",
                                            return_units = "cm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 380),
                                            notes="Applies to female animals",
                                            reference=refs$Pink2013),

           "712470M_PAL~TL_Pink2013" = list(taxon_name = "Macrourus caml",
                                            taxon_aphia_id = 712470,
                                            equation = function(TL) tibble(allometric_value = 1.78 + 0.302 * TL),
                                            inputs = tibble(property = "total length", units = "cm", sample_minimum = 34.5, sample_maximum = 74.5),
                                            return_property = "pre-anal length",
                                            return_units = "cm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 252),
                                            notes="Applies to male animals",
                                            reference=refs$Pink2013),

           "712470M_TL~PAL_Pink2013" = list(taxon_name = "Macrourus caml",
                                            taxon_aphia_id = 712470,
                                            equation = function(PAL) tibble(allometric_value = 1.91 + 2.87 * PAL),
                                            inputs = tibble(property = "pre-anal length", units = "cm"),
                                            return_property = "total length",
                                            return_units = "cm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 252),
                                            notes="Applies to male animals",
                                            reference=refs$Pink2013),

           "234606M_TL~age_Pink2013" = list(taxon_name = "Macrourus whitsoni",
                                            taxon_aphia_id = 234606,
                                            equation = function(t) sol_vonbert(t, Linf = 59.0, k = 0.0947, t0 = -0.159, Linf_se = NA_real_, k_se = 0.0043, t0_se = 0.489),
                                            inputs = tibble(property = "age", units = "yr", sample_minimum = 7, sample_maximum = 24),
                                            return_property = "total length",
                                            return_units = "cm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 37),
                                            notes = "von Bertalanffy growth function for male animals. Note: the age-length data poorly constrained the von Bertalanffy growth curves because of the lack of small and large fish in the sample",
                                            reference = refs$Pink2013),

           "234606F_TL~age_Pink2013" = list(taxon_name = "Macrourus whitsoni",
                                            taxon_aphia_id = 234606,
                                            equation = function(t) sol_vonbert(t, Linf = 65.1, k = 0.101, t0 = 0.159, Linf_se = NA_real_, k_se = 0.0025, t0_se = 0.411),
                                            inputs = tibble(property = "age", units = "yr", sample_minimum = 6, sample_maximum = 27),
                                            return_property = "total length",
                                            return_units = "cm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 190),
                                            notes = "von Bertalanffy growth function for female animals. Note: the age-length data poorly constrained the von Bertalanffy growth curves because of the lack of small and large fish in the sample",
                                            reference = refs$Pink2013),

           "712470M_TL~age_Pink2013" = list(taxon_name = "Macrourus caml",
                                            taxon_aphia_id = 712470,
                                            equation = function(t) sol_vonbert(t, Linf = 76.1, k = 0.0468, t0 = -0.159, Linf_se = 1.93, k_se = 0.0010, t0_se = 0.489),
                                            inputs = tibble(property = "age", units = "yr", sample_minimum = 13, sample_maximum = 62),
                                            return_property = "total length",
                                            return_units = "cm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 129),
                                            notes = "von Bertalanffy growth function for male animals. Note: the age-length data poorly constrained the von Bertalanffy growth curves because of the lack of small and large fish in the sample",
                                            reference = refs$Pink2013),

           "712470F_TL~age_Pink2013" = list(taxon_name = "Macrourus caml",
                                            taxon_aphia_id = 712470,
                                            equation = function(t) sol_vonbert(t, Linf = 92.0, k = 0.0416, t0 = 0.159, Linf_se = 2.27, k_se = 0.0008, t0_se = 0.411),
                                            inputs = tibble(property = "age", units = "yr", sample_minimum = 11, sample_maximum = 46),
                                            return_property = "total length",
                                            return_units = "cm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 190),
                                            notes = "von Bertalanffy growth function for female animals. Note: the age-length data poorly constrained the von Bertalanffy growth curves because of the lack of small and large fish in the sample",
                                            reference = refs$Pink2013),

           stop("unrecognized equation ID: ",id))
}
