refs$Schw2019 <- bibentry(bibtype = "Article", key = "Schw2019",
                          author = c(person("R", "Schwarz"),
                                     person("H-J", "Hoving"),
                                     person("C", "Noever"),
                                     person("U", "Piatkowski")),
                          year = 2019,
                          title = "Life histories of Antarctic incirrate octopods (Cephalopoda: Octopoda)",
                          journal = "PLoS ONE", volume = 14, pages = "e0219694",
                          doi="10.1371/journal.pone.0219694")

alleq_Schw2019 <- function(id) {
    switch(id,
           "325319_WW~DML_Schw2019" = list(taxon_name = "Adelieledone polymorpha",
                                           taxon_aphia_id = 325319,
                                           equation = function(DML) tibble(allometric_value = 1.15e-02 * (DML ^ 2.12)), ## SEs 0.01 and 0.11
                                           inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 20, sample_maximum = 97),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 149,
                                                                 "R^2", 0.77),
                                           notes = "Derived from a sample of male and female animals",
                                           reference = refs$Schw2019),

           "325319M_WW~DML_Schw2019" = list(taxon_name = "Adelieledone polymorpha",
                                            taxon_aphia_id = 325319,
                                            equation = function(DML) tibble(allometric_value = 6.34e-03 * (DML ^ 2.24)), ## SEs 0.01 and 0.23
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 28, sample_maximum = 84),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 66,
                                                                  "R^2", 0.80),
                                            notes = "Applies to male animals",
                                            reference = refs$Schw2019),

           "325319F_WW~DML_Schw2019" = list(taxon_name = "Adelieledone polymorpha",
                                            taxon_aphia_id = 325319,
                                            equation = function(DML) tibble(allometric_value = 7.01e-03 * (DML ^ 2.23)), ## SEs 0.00 and 0.16
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 20, sample_maximum = 97),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 83,
                                                                  "R^2", 0.75),
                                            notes = "Applies to female animals",
                                            reference = refs$Schw2019),

           "325324_WW~DML_Schw2019" = list(taxon_name = "Megaleledone setebos",
                                           taxon_aphia_id = 325324,
                                           equation = function(DML) tibble(allometric_value = 1.39e-04 * (DML ^ 3.32)), ## SEs 0.00 and 0.07
                                           inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 27, sample_maximum = 230),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 59,
                                                                 "R^2", 0.98),
                                           notes = "Derived from a sample of male and female animals",
                                           reference = refs$Schw2019),

           "325324M_WW~DML_Schw2019" = list(taxon_name = "Megaleledone setebos",
                                            taxon_aphia_id = 325324,
                                            equation = function(DML) tibble(allometric_value = 9.89e-07 * (DML ^ 4.23)), ## SEs 0.00 and 0.16
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 27, sample_maximum = 230),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 30,
                                                                  "R^2", 0.97),
                                            notes = "Applies to male animals",
                                            reference = refs$Schw2019),

           "325324F_WW~DML_Schw2019" = list(taxon_name = "Megaleledone setebos",
                                            taxon_aphia_id = 325324,
                                            equation = function(DML) tibble(allometric_value = 2.91e-04 * (DML ^ 3.17)), ## SEs 0.00 and 0.04
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 27, sample_maximum = 160),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 29,
                                                                  "R^2", 0.98),
                                            notes = "Applies to female animals",
                                            reference = refs$Schw2019),

           "527162_WW~DML_Schw2019" = list(taxon_name = "Muusoctopus rigbyae",
                                           taxon_aphia_id = 527162,
                                           equation = function(DML) tibble(allometric_value = 4.29e-03 * (DML ^ 2.44)), ## SEs 0.01 and 0.29
                                           inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 31, sample_maximum = 89),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 59,
                                                                 "R^2", 0.63),
                                           notes = "Derived from a sample of male and female animals",
                                           reference = refs$Schw2019),

           "527162M_WW~DML_Schw2019" = list(taxon_name = "Muusoctopus rigbyae",
                                            taxon_aphia_id = 527162,
                                            equation = function(DML) tibble(allometric_value = 9.32e-04 * (DML ^ 2.79)), ## SEs 0.00 and 0.45
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 47, sample_maximum = 88),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 36,
                                                                  "R^2", 0.65),
                                            notes = "Applies to male animals",
                                            reference = refs$Schw2019),

           "527162F_WW~DML_Schw2019" = list(taxon_name = "Muusoctopus rigbyae",
                                            taxon_aphia_id = 527162,
                                            equation = function(DML) tibble(allometric_value = 5.91-03 * (DML ^ 2.37)), ## SEs 0.01 and 0.43
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 31, sample_maximum = 89),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 23,
                                                                  "R^2", 0.62),
                                            notes = "Applies to female animals",
                                            reference = refs$Schw2019),

           "325325_WW~DML_Schw2019" = list(taxon_name = "Pareledone aequipapillae",
                                           taxon_aphia_id = 325325,
                                           equation = function(DML) tibble(allometric_value = 1.48e-02 * (DML ^ 2.01)), ## SEs 0.01 and 0.09
                                           inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 17, sample_maximum = 78),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 212,
                                                                 "R^2", 0.74),
                                           notes = "Derived from a sample of male and female animals",
                                           reference = refs$Schw2019),

           "325325M_WW~DML_Schw2019" = list(taxon_name = "Pareledone aequipapillae",
                                            taxon_aphia_id = 325325,
                                            equation = function(DML) tibble(allometric_value = 1.83e-02 * (DML ^ 1.95)), ## SEs 0.01 and 0.12
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 21, sample_maximum = 78),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 137,
                                                                  "R^2", 0.67),
                                            notes = "Applies to male animals",
                                            reference = refs$Schw2019),

           "325325F_WW~DML_Schw2019" = list(taxon_name = "Pareledone aequipapillae",
                                            taxon_aphia_id = 325325,
                                            equation = function(DML) tibble(allometric_value = 1.04e-02 * (DML ^ 2.11)), ## SEs 0.01 and 0.16
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 17, sample_maximum = 64),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 75,
                                                                  "R^2", 0.83),
                                            notes = "Applies to female animals",
                                            reference = refs$Schw2019),

           "239392_WW~DML_Schw2019" = list(taxon_name = "Pareledone charcoti",
                                           taxon_aphia_id = 239392,
                                           equation = function(DML) tibble(allometric_value = 2.61e-03 * (DML ^ 2.19)), ## SEs 0.01 and 0.20
                                           inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 18, sample_maximum = 77),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 176,
                                                                 "R^2", 0.80),
                                           notes = "Derived from a sample of male and female animals",
                                           reference = refs$Schw2019),

           "239392M_WW~DML_Schw2019" = list(taxon_name = "Pareledone charcoti",
                                            taxon_aphia_id = 239392,
                                            equation = function(DML) tibble(allometric_value = 4.55e-02 * (DML ^ 1.69)), ## SEs 0.04 and 0.24
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 27, sample_maximum = 57),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 92,
                                                                  "R^2", 0.54),
                                            notes = "Applies to male animals",
                                            reference = refs$Schw2019),

           "239392F_WW~DML_Schw2019" = list(taxon_name = "Pareledone charcoti",
                                            taxon_aphia_id = 239392,
                                            equation = function(DML) tibble(allometric_value = 4.75e-03 * (DML ^ 2.33)), ## SEs 0.00 and 0.09
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 18, sample_maximum = 77),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 84,
                                                                  "R^2", 0.83),
                                            notes = "Applies to female animals",
                                            reference = refs$Schw2019),

           "325336_WW~DML_Schw2019" = list(taxon_name = "Pareledone felix",
                                           taxon_aphia_id = 325336,
                                           equation = function(DML) tibble(allometric_value = 7.54e-03 * (DML ^ 2.19)), ## SEs 0.01 and 0.20
                                           inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 21, sample_maximum = 70),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 61,
                                                                 "R^2", 0.76),
                                           notes = "Derived from a sample of male and female animals",
                                           reference = refs$Schw2019),

           "325336M_WW~DML_Schw2019" = list(taxon_name = "Pareledone felix",
                                            taxon_aphia_id = 325336,
                                            equation = function(DML) tibble(allometric_value = 1.22e-02 * (DML ^ 2.05)), ## SEs 0.02 and 0.33
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 22, sample_maximum = 67),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 38,
                                                                  "R^2", 0.61),
                                            notes = "Applies to male animals",
                                            reference = refs$Schw2019),

           "325336F_WW~DML_Schw2019" = list(taxon_name = "Pareledone felix",
                                            taxon_aphia_id = 325336,
                                            equation = function(DML) tibble(allometric_value = 3.26e-03 * (DML ^ 2.41)), ## SEs 0.00 and 0.28
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 21, sample_maximum = 70),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 23,
                                                                  "R^2", 0.88),
                                            notes = "Applies to female animals",
                                            reference = refs$Schw2019),

           "239393_WW~DML_Schw2019" = list(taxon_name = "Pareledone turqueti",
                                           taxon_aphia_id = 239393,
                                           equation = function(DML) tibble(allometric_value = 9.40e-04 * (DML ^ 2.81)), ## SEs 0.00 and 0.19
                                           inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 6, sample_maximum = 116),
                                           return_property = "wet weight",
                                           return_units = "g",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 70,
                                                                 "R^2", 0.82),
                                           notes = "Derived from a sample of male and female animals",
                                           reference = refs$Schw2019),

           "239393M_WW~DML_Schw2019" = list(taxon_name = "Pareledone turqueti",
                                            taxon_aphia_id = 239393,
                                            equation = function(DML) tibble(allometric_value = 4.01e-04 * (DML ^ 3.01)), ## SEs 0.00 and 0.37
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 6, sample_maximum = 100),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 40,
                                                                  "R^2", 0.75),
                                            notes = "Applies to male animals",
                                            reference = refs$Schw2019),

           "239393F_WW~DML_Schw2019" = list(taxon_name = "Pareledone turqueti",
                                            taxon_aphia_id = 239393,
                                            equation = function(DML) tibble(allometric_value = 5.75e-04 * (DML ^ 2.89)), ## SEs 0.00 and 0.33
                                            inputs = tibble(property = "dorsal mantle length", units = "mm", sample_minimum = 21, sample_maximum = 116),
                                            return_property = "wet weight",
                                            return_units = "g",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 30,
                                                                  "R^2", 0.94),
                                            notes = "Applies to female animals",
                                            reference = refs$Schw2019),

           stop("unrecognized equation ID: ",id))
}
