refs$Goeb2007 <- bibentry(bibtype="Article",key="Goeb2007",
                             author=c(person(c("M","E"),"Goebel"),person(c("J","D"),"Lipsky"),person(c("C","S"),"Reiss"),person(c("V","J"),"Loeb")),
                             year=2007,
                             title="Using carapace measurements to determine the sex of Antarctic krill, Euphausia superba",
                             journal="Polar Biology",volume=30,pages="307-315",
                             doi="10.1007/s00300-006-0184-8")

refs$Morr1988 <- bibentry(bibtype="Article",key="Morr1988",
                             author=c(person(c("D","J"),"Morris"),person(c("J","L"),"Watkins"),person("C","Ricketts"),
                                      person("F","Buchholz"),person("J","Priddle")),
                             year=1988,
                             title="An assessmant of the merits of length and weight measurements of Antarctic krill Euphausia superba",
                             journal="British Antarctic Survey Bulletin",
                             volume=79,pages="27-50")

refs$Hewi2004 <- bibentry(bibtype="Article",key="Hewi2004",
                             author=c(person(c("R","P"),"Hewitt"),person("J","Watkins"),person("M","Naganobu"),
                                      person("V","Sushin"),person(c("A","S"),"Brierley"),person("D","Demer"),
                                      person("S","Kasatkina"),person("Y","Takao"),person("C","Goss"),
                                      person("A","Malyshko"),person("M","Brandon")),
                             year=2004,
                             title="Biomass of Antarctic krill in the Scotia Sea in January/February 2000 and its use in revising an estimate of precautionary yield",
                             journal="Deep Sea Research Part II: Topical Studies in Oceanography",
                             volume=51,pages="1215-1236",doi="10.1016/j.dsr2.2004.06.011")

refs$Mayz2003 <- bibentry(bibtype = "Article", key = "Mayz2003",
                          author = c(person("P", "Mayzaud"),
                                     person("M", "Boutoute"),
                                     person("F", "Alonzo")),
                          year = 2003,
                          title = "Lipid composition of the euphausiids Euphausia vallentini and Thysanoessa macrura during summer in the Southern Indian Ocean",
                          journal = "Antarctic Science",
                          volume = 15, pages = "463-475", doi = "10.1017/S0954102003001573")

##refs$Mayz1998 <- bibentry(bibtype = "Article", key = "Mayz1998",
##                          author = c(person("P", "Mayzaud"),
##                                     person("E", "Albessard"),
##                                     person("J", "Cuzin-Roudy")),
##                          year = 1998,
##                          title = "Changes in lipid composition of the Antarctic krill Euphausia superba  in the Indian sector of the Antarctic Ocean: influence of geographical location, sexual maturity stage and distribution among organs",
##                          journal = "Marine Ecology Progress Series",
##                          volume = 173, pages = "149-162", doi = "10.3354/meps173149")

refs$Farb1994 <- bibentry(bibtype = "Article", key = "Farb1994",
                          author = person("J", "F\ue4rber-Lorda"),
                          year = 1994,
                          title = "Length-weight relationships and coefficient of condition of Euphausia superba and Thysanoessa macrura (Crustacea: Euphausiacea) in southwest Indian Ocean during summer",
                          journal = "Marine Biology",
                          volume = 118, pages = "645-650", doi = "10.1007/BF00347512")

refs$FaMa2010 <- bibentry(bibtype = "Article", key = "FaMa2010",
                          author = c(person("J", "F\ue4rber-Lorda"),
                                     person("P", "Mayzaud")),
                          year = 2010,
                          title = "Morphology and total lipids in Thysanoessa macura from the southern part of the Indian Ocean during summer. Spatial and sex differences",
                          journal = "Deep-Sea Research II",
                          volume = 57, pages = "565-571", doi = "10.1016/j.dsr2.2009.11.001")

refs$Melv2018 <- bibentry(bibtype = "Article", key = "Melv2018",
                          author = c(person(c("J", "E"), "Melvin"),
                                     person("S", "Kawaguchi"),
                                     person("R", "King"),
                                     person(c("K", "M"), "Swadling")),
                          year = 2018,
                          title = "The carapace matters: refinement of the instantaneous growth rate method for Antarctic krill Euphausia superba Dana, 1850 (Euphausiacea)",
                          journal = "Journal of Crustacean Biology",
                          pages = "1-8", doi = "10.1093/jcbiol/ruy069")

refs$PuJo1988 <- bibentry(bibtype = "Article", key = "PuJo1988",
                          author = c(person(c("R", "A"), "Puddicombe"),
                                     person(c("G", "W"), "Johnstone")),
                          year = 1988,
                          title = "The breeding season diet of Adelie penguins at the Vestfold Hills, East Antarctica",
                          journal = "Hydrobiologia",
                          volume = 165, pages = "239-253", doi = "10.1007/bf00025593")

ref$Farb1990 <- bibentry(bibtype = "Article", key = "Farb1990",
                         author = person("J", "F\ue4rber-Lorda"),
                         year = 1990,
                         title = "Somatic length relationships and ontogenetic morphometric differentiation of Euphausia superba and Thysanoessa macrura of the southwest Indian Ocean during summer (February 1981)",
                         journal = "Deep Sea Research Part A Oceanographic Research Papers",
                         volume =  37, pages = "1135-1143", doi = "10.1016/0198-0149(90)90055-Z")

alleq_krill <- function(id) {
    switch(id,
           "236217J_TL_Goeb2007"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(RCL)tibble(allometric_value=10.43+2.26*RCL),
                                     inputs=tibble(property="removed carapace length",units="mm",sample_minimum=9,sample_maximum=12),
                                     return_property="total length",
                                     return_units="mm",
                                     reliability=tribble(~type,~value,
                                                         "N",154,
                                                         "R^2",0.40),
                                     notes="Applies to juvenile animals",
                                     reference=refs$Goeb2007),
           "236217F_TL_Goeb2007"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(RCL)tibble(allometric_value=11.6+2.13*RCL),
                                     inputs=tibble(property="removed carapace length",units="mm",sample_minimum=9,sample_maximum=21),
                                     return_property="total length",
                                     return_units="mm",
                                     reliability=tribble(~type,~value,
                                                         "N",463,
                                                         "R^2",0.883),
                                     notes="Applies to adult female animals",
                                     reference=refs$Goeb2007),
           "236217M_TL_Goeb2007"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(RCL)tibble(allometric_value=0.62+3.13*RCL),
                                     inputs=tibble(property="removed carapace length",units="mm",sample_minimum=9,sample_maximum=18),
                                     return_property="total length",
                                     return_units="mm",
                                     reliability=tribble(~type,~value,
                                                         "N",514,
                                                         "R^2",0.777),
                                     notes="Applies to adult male animals",
                                     reference=refs$Goeb2007),

           "236217_WW_Morr1988"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(AT){ a <- 3.85; expon <- 3.20;
                                         out <- a*1e-06*(AT^expon)
                                         tibble(allometric_value=replace(out,AT<22 | AT>48,NA))},
                                     inputs=tibble(property="total length",units="mm",sample_minimum=22,sample_maximum=48),
                                     return_property="wet weight",
                                     return_units="g",
                                     reliability=tribble(~type,~value,
                                                         "N",4217),
                                     notes="Parameters from Morris et al. (1988) Table IV. Equation may not be valid outside of the range of data used to fit the equation; such values set to NA here",
                                     reference=refs$Morr1988),

           "236217_WW_Hewi2004"=list(taxon_name="Euphausia superba",
                                     taxon_aphia_id=236217,
                                     equation=function(SL){ a <- 2.236; expon <- 3.314;
                                         out <- a*1e-06*(SL^expon)
                                         tibble(allometric_value=out)},
                                     inputs=tibble(property="standard length",units="mm"),
                                     return_property="wet weight",
                                     return_units="g",
                                     notes="Parameters from Hewitt et al. (2004) equ. 3",
                                     reference=refs$Hewi2004),

           ## Mayz2003
           ## Thysanoessa macrura  236219
           "236219A_WW~TL_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                                taxon_aphia_id = 236219,
                                                equation = function(TL) tibble(allometric_value = 10^(4.38 * log10(TL) - 3.64)),
                                                inputs = tibble(property = "total length", units = "mm"),
                                                return_property = "wet weight",
                                                return_units = "mg",
                                                reliability = tribble(~type, ~value,
                                                                      "N", 23,
                                                                      "R^2", 0.814),
                                                notes = "Applies to adult animals",
                                                reference = refs$Mayz2003),

           "236219J_WW~TL_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                                   taxon_aphia_id = 236219,
                                                   equation = function(TL) tibble(allometric_value = 10^(2.83 * log10(TL) - 1.72)),
                                                   inputs = tibble(property = "total length", units = "mm"),
                                                   return_property = "wet weight",
                                                   return_units = "mg",
                                                   reliability = tribble(~type, ~value,
                                                                         "N", 37,
                                                                         "R^2", 0.859),
                                                   notes = "Applies to juvenile animals",
                                                   reference = refs$Mayz2003),
           ## Euphausia vallentini  221054
           "221054M_WW~TL_Mayz2003" = list(taxon_name = "Euphausia vallentini",
                                           taxon_aphia_id = 221054,
                                           equation = function(TL) tibble(allometric_value = 10^(2.60 * log10(TL) - 1.53)),
                                           inputs = tibble(property = "total length", units = "mm"),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 57,
                                                                 "R^2", 0.804),
                                           notes = "Applies to male animals",
                                           reference = refs$Mayz2003),
           "221054F_WW~TL_Mayz2003" = list(taxon_name = "Euphausia vallentini",
                                           taxon_aphia_id = 221054,
                                           equation = function(TL) tibble(allometric_value = 10^(1.87 * log10(TL) - 0.52)),
                                           inputs = tibble(property = "total length", units = "mm"),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 71,
                                                                 "R^2", 0.575),
                                           notes = "Applies to female animals",
                                           reference = refs$Mayz2003),

           ## lipid weights to wet weights
           "221054_LpW~WW_Mayz2003" = list(taxon_name = "Euphausia vallentini",
                                           taxon_aphia_id = 221054,
                                           equation = function(WW) tibble(allometric_value = 10^(2.39 * log10(WW) - 5.01)),
                                           inputs = tibble(property = "wet weight", units = "mg"),
                                           return_property = "lipid weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 26,
                                                                 "R^2", 0.757),
                                           notes = "No difference between sexes observed, so equation was derived from data from males and females combined",
                                           reference = refs$Mayz2003),

           "236219F_LpW~WW_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(WW) tibble(allometric_value = 10^(2.86 * log10(WW) - 4.97)),
                                           inputs = tibble(property = "wet weight", units = "mg"),
                                           return_property = "lipid weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 17,
                                                                 "R^2", 0.792),
                                           notes = "Applies to female animals",
                                           reference = refs$Mayz2003),

           "236219M_LpW~WW_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                            taxon_aphia_id = 236219,
                                            equation = function(WW) tibble(allometric_value = 10^(1.53 * log10(WW) - 2.80)),
                                            inputs = tibble(property = "wet weight", units = "mg"),
                                            return_property = "lipid weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 6,
                                                                  "R^2", 0.835),
                                            notes = "Applies to male animals",
                                            reference = refs$Mayz2003),

           "236219J_LpW~WW_Mayz2003" = list(taxon_name = "Thysanoessa macrura",
                                            taxon_aphia_id = 236219,
                                            equation = function(WW) tibble(allometric_value = 10^(1.04 * log10(WW) - 1.65)),
                                            inputs = tibble(property = "wet weight", units = "mg"),
                                            return_property = "lipid weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 37,
                                                                  "R^2", 0.300),
                                            notes = "Applies to juvenile animals",
                                            reference = refs$Mayz2003),


##           ## Mayzaud et al 1998
##           ## Euphausia superba 236217,
##           "236217_WW~TL_Mayz1998" = list(taxon_name="Euphausia superba",
##                                          taxon_aphia_id=236217,
##                                          equation = function(TL) tibble(allometric_value = 10^(-0.08 + 3.12 * log10(TL))),
##                                          inputs = tibble(property = "total length", units = "mm"),
##                                          return_property = "wet weight",
##                                          return_units = "mg",
##                                          reliability = tribble(~type, ~value,
##                                                                "N", 121,
##                                                                "R^2", 0.967),
##                                          notes = "Applies to males, females, and subadult animals",
##                                          reference = refs$Mayz1998),
           ## this looks wrong, it doesn't match the figure in the paper. Not including


           ## Farber-Lorda 1994
           "236219_WW~TL_Farb1994" = list(taxon_name = "Thysanoessa macrura",
                                          taxon_aphia_id = 236219,
                                          equation = function(TL) tibble(allometric_value = 0.00157 * (TL ^ 3.721)),
                                          inputs = tibble(property = "total length", units = "mm", sample_minimum = 8.87, sample_maximum = 21.82),
                                          return_property = "wet weight",
                                          return_units = "mg",
                                          reliability = tribble(~type, ~value,
                                                                "N", 106,
                                                                "R^2", 0.911),
                                          notes = "Applies to males, females, and subadult animals",
                                          reference = refs$Farb1994),

           "236219SA_WW~TL_Farb1994" = list(taxon_name = "Thysanoessa macrura",
                                            taxon_aphia_id = 236219,
                                            equation = function(TL) tibble(allometric_value = 1.65e-03 * (TL ^ 3.705)),
                                            inputs = tibble(property = "total length", units = "mm", sample_minimum = 8.87, sample_maximum = 16.92),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 70),
                                            notes = "Applies to subadult animals",
                                            reference = refs$Farb1994),

           "236219A_WW~TL_Farb1994" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(TL) tibble(allometric_value = 0.13e-03 * (TL ^ 4.564)),
                                           inputs = tibble(property = "total length", units = "mm", sample_minimum = 17.2, sample_maximum = 21.82),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 36),
                                           notes = "Applies to adult animals of both sexes",
                                           reference = refs$Farb1994),

           "236219M_WW~TL_Farb1994" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(TL) tibble(allometric_value = 0.20e-03 * (TL ^ 4.382)),
                                           inputs = tibble(property = "total length", units = "mm", sample_minimum = 17.22, sample_maximum = 21.05),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 15),
                                           notes = "Applies to adult male animals",
                                           reference = refs$Farb1994),

           "236219F_WW~TL_Farb1994" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(TL) tibble(allometric_value = 1.25e-03 * (TL ^ 3.824)),
                                           inputs = tibble(property = "total length", units = "mm", sample_minimum = 17.2, sample_maximum = 21.82),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 21),
                                           notes = "Applies to adult female animals",
                                           reference = refs$Farb1994),

           "236219SA_WW~CL_Farb1994" = list(taxon_name = "Thysanoessa macrura",
                                            taxon_aphia_id = 236219,
                                            equation = function(CL) tibble(allometric_value = 0.215 * (CL ^ 3.330)),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 2.86, sample_maximum = 5.73),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 70),
                                            notes = "Applies to subadult animals",
                                            reference = refs$Farb1994),

           "236219A_WW~CL_Farb1994" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(CL) tibble(allometric_value = 0.279 * (CL ^ 3.120)),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 5.27, sample_maximum = 7.80),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 36),
                                           notes = "Applies to adult animals of both sexes",
                                           reference = refs$Farb1994),

           "236219M_WW~CL_Farb1994" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(CL) tibble(allometric_value = 0.076 * (CL ^ 3.826)),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 5.29, sample_maximum = 6.70),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 14),
                                           notes = "Applies to adult male animals",
                                           reference = refs$Farb1994),

           "236219F_WW~CL_Farb1994" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(CL) tibble(allometric_value = 0.833 * (CL ^ 2.559)),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 5.27, sample_maximum = 7.80),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 22),
                                           notes = "Applies to adult female animals",
                                           reference = refs$Farb1994),

           "236217_WW~TL_Farb1994" = list(taxon_name = "Euphausia superba",
                                          taxon_aphia_id = 236217,
                                          equation = function(TL) tibble(allometric_value = 0.00503 * (TL ^ 3.283)),
                                          inputs = tibble(property = "total length", units = "mm", sample_minimum = 22.8, sample_maximum = 49.1),
                                          return_property = "wet weight",
                                          return_units = "mg",
                                          reliability = tribble(~type, ~value,
                                                                "N", 343,
                                                                "R^2", 0.946),
                                          notes = "Applies to males, females (mature and spawned), and subadult animals",
                                          reference = refs$Farb1994),

           "236217SA_WW~TL_Farb1994" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(TL) tibble(allometric_value = 7.16e-03 * (TL ^ 3.183)),
                                            inputs = tibble(property = "total length", units = "mm", sample_minimum = 22.8, sample_maximum = 35.0),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 161),
                                            notes = "Applies to subadult animals",
                                            reference = refs$Farb1994),

           "236217MI_WW~TL_Farb1994" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(TL) tibble(allometric_value = 2.32e-03 * (TL ^ 3.490)),
                                            inputs = tibble(property = "total length", units = "mm", sample_minimum = 33.3, sample_maximum = 41.2),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 45),
                                            notes = "Applies to male stage I animals",
                                            reference = refs$Farb1994),

           "236217MII_WW~TL_Farb1994" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(TL) tibble(allometric_value = 2.72e-03 * (TL ^ 3.463)),
                                            inputs = tibble(property = "total length", units = "mm", sample_minimum = 36.0, sample_maximum = 43.0),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 24),
                                            notes = "Applies to male stage II animals",
                                            reference = refs$Farb1994),

           "236217F_WW~TL_Farb1994" = list(taxon_name = "Euphausia superba",
                                           taxon_aphia_id = 236217,
                                           equation = function(TL) tibble(allometric_value = 5.87e-03 * (TL ^ 3.247)),
                                           inputs = tibble(property = "total length", units = "mm", sample_minimum = 33.4, sample_maximum = 49.1),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 62),
                                           notes = "Applies to mature female animals",
                                           reference = refs$Farb1994),

           "236217SF_WW~TL_Farb1994" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(TL) tibble(allometric_value = 1.70e-03 * (TL ^ 3.562)),
                                            inputs = tibble(property = "total length", units = "mm", sample_minimum = 33.9, sample_maximum = 43.7),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 53),
                                            notes = "Applies to spawned female animals",
                                            reference = refs$Farb1994),

           "236217SA_WW~CL_Farb1994" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(CL) tibble(allometric_value = 35.87e-03 * (CL ^ 3.701)),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 8.7, sample_maximum = 14.1),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 86),
                                            notes = "Applies to subadult animals",
                                            reference = refs$Farb1994),

           "236217MI_WW~CL_Farb1994" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(CL) tibble(allometric_value = 24.79e-03 * (CL ^ 3.841)),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12.1, sample_maximum = 15.5),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 45),
                                            notes = "Applies to male stage I animals",
                                            reference = refs$Farb1994),

           "236217MII_WW~CL_Farb1994" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(CL) tibble(allometric_value = 29.04e-03 * (CL ^ 3.955)),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12.4, sample_maximum = 15.4),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 24),
                                            notes = "Applies to male stage II animals",
                                            reference = refs$Farb1994),

           "236217F_WW~CL_Farb1994" = list(taxon_name = "Euphausia superba",
                                           taxon_aphia_id = 236217,
                                           equation = function(CL) tibble(allometric_value = 25.77e-03 * (CL ^ 3.714)),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12.8, sample_maximum = 20.3),
                                           return_property = "wet weight",
                                           return_units = "mg",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 43),
                                           notes = "Applies to mature female animals",
                                           reference = refs$Farb1994),

           "236217SF_WW~CL_Farb1994" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(CL) tibble(allometric_value = 26.68e-03 * (CL ^ 3.687)),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 13.8, sample_maximum = 18.8),
                                            return_property = "wet weight",
                                            return_units = "mg",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 32),
                                            notes = "Applies to spawned female animals",
                                            reference = refs$Farb1994),

           "236217F_TL~CL_Melv2018" = list(taxon_name = "Euphausia superba",
                                           taxon_aphia_id = 236217,
                                           equation = function(CL) tibble(allometric_value = -3.23 + 0.422*CL),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 26, sample_maximum = 52),
                                           return_property = "total length",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 93,
                                                                 "R^2", 0.89),
                                           notes = "Applies to post-moult female animals",
                                           reference = refs$Melv2018),
           "236217M_TL~CL_Melv2018" = list(taxon_name = "Euphausia superba",
                                           taxon_aphia_id = 236217,
                                           equation = function(CL) tibble(allometric_value = -0.304 + 0.33*CL),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 25, sample_maximum = 51),
                                           return_property = "total length",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 46,
                                                                 "R^2", 0.89),
                                           notes = "Applies to post-moult male animals",
                                           reference = refs$Melv2018),

           "236216_TL~CL_PuJo1988" = list(taxon_name = "Euphausia crystallorophias",
                                          taxon_aphia_id = 236216,
                                          equation = function(CL) tibble(allometric_value = 1.512*CL + 13.28),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 5.2, sample_maximum = 13.8),
                                          return_property = "total length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 343),
                                          reference = refs$PuJo1988),

           "236217_TL~CL_PuJo1988" = list(taxon_name = "Euphausia superba",
                                          taxon_aphia_id = 236217,
                                          equation = function(CL) tibble(allometric_value = 2.857*CL + 2.63),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 6.2, sample_maximum = 19.0),
                                          return_property = "total length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 262),
                                          reference = refs$PuJo1988),

           "236219_ED~CL_FaMa2010" = list(taxon_name = "Thysanoessa macrura",
                                          taxon_aphia_id = 236219,
                                          equation = function(CL) tibble(allometric_value = 0.9807*(CL^0.4187)),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 3.5, sample_maximum = 7.8),
                                          return_property = "eye diameter",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 41,
                                                                "R^2", 0.764),
                                          notes = "Sample minimum and maximum are approximate",
                                          reference = refs$FaMa2010),

           "236219_ED~TL_FaMa2010" = list(taxon_name = "Thysanoessa macrura",
                                          taxon_aphia_id = 236219,
                                          equation = function(TL) tibble(allometric_value = 0.4361*(TL^0.5411)),
                                          inputs = tibble(property = "total length", units = "mm", sample_minimum = 12, sample_maximum = 21.5),
                                          return_property = "eye diameter",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 41,
                                                                "R^2", 0.818),
                                          notes = "Sample minimum and maximum are approximate",
                                          reference = refs$FaMa2010),

           "236219_ED~WW_FaMa2010" = list(taxon_name = "Thysanoessa macrura",
                                          taxon_aphia_id = 236219,
                                          equation = function(WW) tibble(allometric_value = 1.04*(WW^0.1557)),
                                          inputs = tibble(property = "wet weight", units = "mg", sample_minimum = 15, sample_maximum = 160),
                                          return_property = "eye diameter",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 41,
                                                                "R^2", 0.8198),
                                          notes = "Sample minimum and maximum are approximate",
                                          reference = refs$FaMa2010),

           "236219_CL~TL_FaMa2010" = list(taxon_name = "Thysanoessa macrura",
                                          taxon_aphia_id = 236219,
                                          equation = function(TL) tibble(allometric_value = 0.1699*(TL^1.232)),
                                          inputs = tibble(property = "total length", units = "mm", sample_minimum = 12, sample_maximum = 21.5),
                                          return_property = "carapace length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 60,
                                                                "R^2", 0.975),
                                          notes = "Sample minimum and maximum are approximate",
                                          reference = refs$FaMa2010),

           "236219_WW~TL_FaMa2010" = list(taxon_name = "Thysanoessa macrura",
                                          taxon_aphia_id = 236219,
                                          equation = function(TL) tibble(allometric_value = 0.002098*(TL^3.6446)),
                                          inputs = tibble(property = "total length", units = "mm", sample_minimum = 12, sample_maximum = 21.5),
                                          return_property = "carapace length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 60,
                                                                "R^2", 0.9529),
                                          notes = "Sample minimum and maximum are approximate",
                                          reference = refs$FaMa2010),

           "236219_WW~CL_FaMa2010" = list(taxon_name = "Thysanoessa macrura",
                                          taxon_aphia_id = 236219,
                                          equation = function(CL) tibble(allometric_value = 0.5335*(CL^2.793)),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 3.5, sample_maximum = 7.8),
                                          return_property = "wet weight",
                                          return_units = "mg",
                                          reliability = tribble(~type, ~value,
                                                                "N", 60,
                                                                "R^2", 0.960),
                                          notes = "Sample minimum and maximum are approximate",
                                          reference = refs$FaMa2010),

           "236219_LpWW~WW_FaMa2010" = list(taxon_name = "Thysanoessa macrura",
                                            taxon_aphia_id = 236219,
                                            equation = function(WW) tibble(allometric_value = 0.0003721 * (WW ^ 1.098) * 100),
                                            inputs = tibble(property = "wet weight", units = "mg", sample_minimum = 15, sample_maximum = 160),
                                            return_property = "lipid content wet weight",
                                            return_units = "%",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 60,
                                                                  "R^2", 0.770),
                                            notes = "Sample minimum and maximum are approximate. Adapted from F\ue4rber-Lorda & Mayzaud (2010) figure 9 and its corresponding equation",
                                            reference = refs$FaMa2010),

           "236217SAJ_TL~CL_Farb1990" = list(taxon_name = "Euphausia superba",
                                             taxon_aphia_id = 236217,
                                             equation = function(CL) tibble(allometric_value = 2.376 * CL + 2.182),
                                             inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 8, sample_maximum = 14),
                                             return_property = "total length",
                                             return_units = "mm",
                                             reliability = tribble(~type, ~value,
                                                                   "N", 147,
                                                                   "R^2", 0.94),
                                             notes = "Applies to subadult and juvenile animals. Sample minimum and maximum are approximate.",
                                             reference = refs$Farb1990),

           "236217M1_TL~CL_Farb1990" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(CL) tibble(allometric_value = 2.131 * CL + 6.753),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12, sample_maximum = 16),
                                            return_property = "total length",
                                            return_units = "mm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 120,
                                                                  "R^2", 0.74),
                                            notes = "Applies to male animals from Group 1 (as defined by F\ue4rber-Lorda 1990). Sample minimum and maximum are approximate.",
                                            reference = refs$Farb1990),

           "236217M2_TL~CL_Farb1990" = list(taxon_name = "Euphausia superba",
                                            taxon_aphia_id = 236217,
                                            equation = function(CL) tibble(allometric_value = 2.748 * CL + 1.869),
                                            inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 12, sample_maximum = 15.5),
                                            return_property = "total length",
                                            return_units = "mm",
                                            reliability = tribble(~type, ~value,
                                                                  "N", 60,
                                                                  "R^2", 0.73),
                                            notes = "Applies to male animals from Group 2 (as defined by F\ue4rber-Lorda 1990). Sample minimum and maximum are approximate.",
                                            reference = refs$Farb1990),

           "236217F_TL~CL_Farb1990" = list(taxon_name = "Euphausia superba",
                                           taxon_aphia_id = 236217,
                                           equation = function(CL) tibble(allometric_value = 1.836 * CL + 9.139),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 13, sample_maximum = 21),
                                           return_property = "total length",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 112,
                                                                 "R^2", 0.88),
                                           notes = "Applies to female animals. Sample minimum and maximum are approximate.",
                                           reference = refs$Farb1990),

           "236219J_TL~CL_Farb1990" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(CL) tibble(allometric_value = 2.719 * CL + 2.112),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 2.5, sample_maximum = 5.5),
                                           return_property = "total length",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 173,
                                                                 "R^2", 0.92),
                                           notes = "Applies to juvenile animals. Sample minimum and maximum are approximate",
                                           reference = refs$Farb1990),

           "236219M_TL~CL_Farb1990" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(CL) tibble(allometric_value = 2.060 * CL + 5.602),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 5, sample_maximum = 7),
                                           return_property = "total length",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 33,
                                                                 "R^2", 0.85),
                                           notes = "Applies to adult male animals. Sample minimum and maximum are approximate",
                                           reference = refs$Farb1990),

           "236219F_TL~CL_Farb1990" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(CL) tibble(allometric_value = 2.132 * CL + 4.607),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 5.5, sample_maximum = 8),
                                           return_property = "total length",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 41,
                                                                 "R^2", 0.89),
                                           notes = "Applies to adult female animals. Sample minimum and maximum are approximate",
                                           reference = refs$Farb1990),

           "236219A_TL~CL_Farb1990" = list(taxon_name = "Thysanoessa macrura",
                                           taxon_aphia_id = 236219,
                                           equation = function(CL) tibble(allometric_value = 1.857 * CL + 7.142),
                                           inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 5.5, sample_maximum = 8),
                                           return_property = "total length",
                                           return_units = "mm",
                                           reliability = tribble(~type, ~value,
                                                                 "N", 75,
                                                                 "R^2", 0.87),
                                           notes = "Applies to adult animals. Sample minimum and maximum are approximate",
                                           reference = refs$Farb1990),

           "236219_TL~CL_Farb1990" = list(taxon_name = "Thysanoessa macrura",
                                          taxon_aphia_id = 236219,
                                          equation = function(CL) tibble(allometric_value = 4.221 * (CL ^ 0.812)),
                                          inputs = tibble(property = "carapace length", units = "mm", sample_minimum = 2.5, sample_maximum = 8),
                                          return_property = "total length",
                                          return_units = "mm",
                                          reliability = tribble(~type, ~value,
                                                                "N", 249),
                                          notes = "Derived from a combined sample of juvenile and adult male and female animals. Sample minimum and maximum are approximate",
                                          reference = refs$Farb1990),

           stop("unrecognized equation ID: ",id))
}
